/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DogTrainerAppCommandResponse } from '../../models/dog-trainer-app-command-response';
import { DogTrainerRequest } from '../../models/dog-trainer-request';

export interface ApiDogTrainerAppAnonymousSubmitPost$Params {
  
    /**
     * DogTrainerRequest data
     */
    body?: DogTrainerRequest
}

export function apiDogTrainerAppAnonymousSubmitPost(http: HttpClient, rootUrl: string, params?: ApiDogTrainerAppAnonymousSubmitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<DogTrainerAppCommandResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDogTrainerAppAnonymousSubmitPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DogTrainerAppCommandResponse>;
    })
  );
}

apiDogTrainerAppAnonymousSubmitPost.PATH = '/api/dog-trainer-app/anonymous/submit';
