/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DogTrainerAppResponse } from '../../models/dog-trainer-app-response';

export interface ApiDogTrainerAppGet$Params {
}

export function apiDogTrainerAppGet(http: HttpClient, rootUrl: string, params?: ApiDogTrainerAppGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DogTrainerAppResponse>> {
  const rb = new RequestBuilder(rootUrl, apiDogTrainerAppGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DogTrainerAppResponse>;
    })
  );
}

apiDogTrainerAppGet.PATH = '/api/dog-trainer-app';
