/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LicenceBasicResponse } from '../../models/licence-basic-response';

export interface ApiLicencesSecurityWorkerLicenceGet$Params {
  licenceNumber?: string;
  firstName?: string;
  lastName?: string;
}

export function apiLicencesSecurityWorkerLicenceGet(http: HttpClient, rootUrl: string, params?: ApiLicencesSecurityWorkerLicenceGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LicenceBasicResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiLicencesSecurityWorkerLicenceGet.PATH, 'get');
  if (params) {
    rb.query('licenceNumber', params.licenceNumber, {});
    rb.query('firstName', params.firstName, {});
    rb.query('lastName', params.lastName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LicenceBasicResponse>>;
    })
  );
}

apiLicencesSecurityWorkerLicenceGet.PATH = '/api/licences/security-worker-licence';
