/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LicenceBasicAnonResponse } from '../../models/licence-basic-anon-response';
import { LicenceNumbersRequest } from '../../models/licence-numbers-request';

export interface ApiLicencesSecurityWorkerLicenceInBulkPost$Params {
      body?: LicenceNumbersRequest
}

export function apiLicencesSecurityWorkerLicenceInBulkPost(http: HttpClient, rootUrl: string, params?: ApiLicencesSecurityWorkerLicenceInBulkPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LicenceBasicAnonResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiLicencesSecurityWorkerLicenceInBulkPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LicenceBasicAnonResponse>>;
    })
  );
}

apiLicencesSecurityWorkerLicenceInBulkPost.PATH = '/api/licences/security-worker-licence-in-bulk';
