/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GoogleRecaptcha } from '../../models/google-recaptcha';
import { LicenceBasicResponse } from '../../models/licence-basic-response';

export interface ApiLicencesBusinessLicencePost$Params {
  licenceNumber?: string;
  businessName?: string;
      body?: GoogleRecaptcha
}

export function apiLicencesBusinessLicencePost(http: HttpClient, rootUrl: string, params?: ApiLicencesBusinessLicencePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LicenceBasicResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiLicencesBusinessLicencePost.PATH, 'post');
  if (params) {
    rb.query('licenceNumber', params.licenceNumber, {});
    rb.query('businessName', params.businessName, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LicenceBasicResponse>>;
    })
  );
}

apiLicencesBusinessLicencePost.PATH = '/api/licences/business-licence';
