/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LicenceBasicResponse } from '../../models/licence-basic-response';

export interface ApiApplicantsApplicantIdGdsdCertificationsGet$Params {
  applicantId: string;
}

export function apiApplicantsApplicantIdGdsdCertificationsGet(http: HttpClient, rootUrl: string, params: ApiApplicantsApplicantIdGdsdCertificationsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LicenceBasicResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiApplicantsApplicantIdGdsdCertificationsGet.PATH, 'get');
  if (params) {
    rb.path('applicantId', params.applicantId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LicenceBasicResponse>>;
    })
  );
}

apiApplicantsApplicantIdGdsdCertificationsGet.PATH = '/api/applicants/{applicantId}/gdsd-certifications';
