name-template: "Release v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: 🚀 New Features
    labels:
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🧹 Chores
    labels:
      - chore
change-template: "- ${{PR.title}} (#${{PR.number}}) by @${{PR.author}}"
no-changes-template: "- No changes in this release."
sort-by: "merged_at"
sort-direction: "descending"
