/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdirUserProfileResponse } from '../../models/idir-user-profile-response';

export interface ApiIdirUsersUserIdLoginGet$Params {
  userId: string;
}

export function apiIdirUsersUserIdLoginGet(http: HttpClient, rootUrl: string, params: ApiIdirUsersUserIdLoginGet$Params, context?: HttpContext): Observable<StrictHttpResponse<IdirUserProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, apiIdirUsersUserIdLoginGet.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdirUserProfileResponse>;
    })
  );
}

apiIdirUsersUserIdLoginGet.PATH = '/api/idir-users/{userId}/login';
