/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddressFindResponse {
  cursor?: number | null;
  description?: string | null;
  highlight?: string | null;
  id?: string | null;
  next?: string | null;
  text?: string | null;
}
