/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ApplicationTypeCode {
  New = 'New',
  Renewal = 'Renewal',
  Replacement = 'Replacement',
  Update = 'Update'
}
