/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicantListResponse {
  applicantId?: string;
  birthDate?: string;
  firstName?: string | null;
  lastName?: string | null;
  licenceExpiryDate?: string | null;
  licenceNumber?: string | null;
  middleName1?: string | null;
  middleName2?: string | null;
}
