/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicantApplicationFileResponse } from '../models/applicant-application-file-response';
export interface ApplicantApplicationFileListResponse {
  items?: Array<ApplicantApplicationFileResponse> | null;
}
