/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicationCreateResponse {
  applicationId?: string | null;
  createSuccess?: boolean;
  hasPotentialDuplicate?: boolean;
  isDuplicateCheckRequired?: boolean;
}
