/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationPaymentResponse } from '../models/application-payment-response';
import { PaginationResponse } from '../models/pagination-response';
export interface ApplicationPaymentListResponse {
  applications?: Array<ApplicationPaymentResponse> | null;
  pagination?: PaginationResponse;
}
