/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicantApplicationResponse } from '../models/applicant-application-response';
export interface ApplicantApplicationListResponse {
  applications?: Array<ApplicantApplicationResponse> | null;
}
