/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationInviteCreateRequest } from '../models/application-invite-create-request';
export interface ApplicationInvitesCreateRequest {
  applicationInviteCreateRequests?: Array<ApplicationInviteCreateRequest> | null;
  hostUrl?: string | null;
  requireDuplicateCheck?: boolean;
}
