/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ArmouredVehiclePermitReasonCode {
  ProtectionOfPersonalProperty = 'ProtectionOfPersonalProperty',
  ProtectionOfOtherProperty = 'ProtectionOfOtherProperty',
  ProtectionOfAnotherPerson = 'ProtectionOfAnotherPerson',
  PersonalProtection = 'PersonalProtection',
  MyEmployment = 'MyEmployment',
  Other = 'Other'
}
