/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactAuthorizationTypeCode } from '../models/contact-authorization-type-code';
export interface BizPortalUserCreateRequest {
  bizId?: string;
  contactAuthorizationTypeCode?: ContactAuthorizationTypeCode;
  email?: string | null;
  firstName?: string | null;
  jobTitle?: string | null;
  lastName?: string | null;
  phoneNumber?: string | null;
}
