/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum BizTypeCode {
  NonRegisteredSoleProprietor = 'NonRegisteredSoleProprietor',
  NonRegisteredPartnership = 'NonRegisteredPartnership',
  RegisteredSoleProprietor = 'RegisteredSoleProprietor',
  RegisteredPartnership = 'RegisteredPartnership',
  Corporation = 'Corporation',
  None = 'None'
}
