/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum BodyArmourPermitReasonCode {
  PersonalProtection = 'PersonalProtection',
  MyEmployment = 'MyEmployment',
  OutdoorRecreation = 'OutdoorRecreation',
  TravelInResponseToInternationalConflict = 'TravelInResponseToInternationalConflict',
  Other = 'Other'
}
