/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BulkAppsCreateResponse } from '../models/bulk-apps-create-response';
import { DuplicateCheckResult } from '../models/duplicate-check-result';
import { ValidationErr } from '../models/validation-err';
export interface BulkUploadCreateResponse {
  createResponse?: BulkAppsCreateResponse;
  duplicateCheckResponses?: Array<DuplicateCheckResult> | null;
  validationErrs?: Array<ValidationErr> | null;
}
