/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum CaseSubStatusCode {
  ApplicantInformation = 'ApplicantInformation',
  Fingerprints = 'Fingerprints',
  SelfDisclosure = 'SelfDisclosure',
  OpportunityToRespond = 'OpportunityToRespond'
}
