/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClearanceAccessResponse {
  clearanceId?: string;
  email?: string | null;
  expiresOn?: string | null;
  facility?: string | null;
  firstName?: string | null;
  id?: string;
  lastName?: string | null;
  status?: string | null;
}
