/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OidcConfiguration } from '../models/oidc-configuration';
import { RecaptchaConfiguration } from '../models/recaptcha-configuration';
export interface ConfigurationResponse {
  bannerMessage?: string | null;
  bcscConfiguration?: OidcConfiguration;
  environment?: string | null;
  recaptchaConfiguration?: RecaptchaConfiguration;
  version?: string | null;
}
