/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactInfo {
  emailAddress?: string | null;
  givenName?: string | null;
  middleName1?: string | null;
  middleName2?: string | null;
  phoneNumber?: string | null;
  surname?: string | null;
}
