/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LicenceDocumentTypeCode } from '../models/licence-document-type-code';
export interface DocumentRelatedInfo {
  documentIdNumber?: string | null;
  expiryDate?: string | null;
  licenceDocumentTypeCode?: LicenceDocumentTypeCode;
}
