/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LicenceDocumentTypeCode } from '../models/licence-document-type-code';
export interface Document {
  documentExtension?: string | null;
  documentIdNumber?: string | null;
  documentName?: string | null;
  documentUrlId?: string;
  expiryDate?: string | null;
  licenceAppId?: string | null;
  licenceDocumentTypeCode?: LicenceDocumentTypeCode;
  uploadedDateTime?: string;
}
