/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BizTypeCode } from '../models/biz-type-code';
import { DocumentRelatedInfo } from '../models/document-related-info';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { ServiceTypeCode } from '../models/service-type-code';
export interface DogTrainerRequest {
  accreditedSchoolId?: string;
  accreditedSchoolName?: string | null;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizTypeCode?: BizTypeCode;
  documentKeyCodes?: Array<string> | null;
  documentRelatedInfos?: Array<DocumentRelatedInfo> | null;
  licenceTermCode?: LicenceTermCode;
  schoolContactEmailAddress?: string | null;
  schoolContactPhoneNumber?: string | null;
  schoolDirectorGivenName?: string | null;
  schoolDirectorMiddleName?: string | null;
  schoolDirectorSurname?: string | null;
  serviceTypeCode?: ServiceTypeCode;
  trainerDateOfBirth?: string | null;
  trainerEmailAddress?: string | null;
  trainerGivenName?: string | null;
  trainerMailingAddress?: MailingAddress;
  trainerMiddleName?: string | null;
  trainerPhoneNumber?: string | null;
  trainerSurname?: string | null;
}
