/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DogSchoolResponse {
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  contactEmailAddress?: string | null;
  contactPhoneNumber?: string | null;
  country?: string | null;
  id?: string;
  postalCode?: string | null;
  province?: string | null;
  schoolLegalName?: string | null;
  schoolName?: string | null;
}
