/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum EmployeeInteractionTypeCode {
  Children = 'Children',
  Adults = 'Adults',
  ChildrenAndAdults = 'ChildrenAndAdults',
  Neither = 'Neither'
}
