/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccreditedSchoolQuestions } from '../models/accredited-school-questions';
import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BizTypeCode } from '../models/biz-type-code';
import { DocumentRelatedInfo } from '../models/document-related-info';
import { DogInfo } from '../models/dog-info';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { NonAccreditedSchoolQuestions } from '../models/non-accredited-school-questions';
import { ServiceTypeCode } from '../models/service-type-code';
export interface GdsdTeamLicenceAppAnonymousSubmitRequest {
  accreditedSchoolQuestions?: AccreditedSchoolQuestions;
  applicantOrLegalGuardianName?: string | null;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizTypeCode?: BizTypeCode;
  dateOfBirth?: string | null;
  documentKeyCodes?: Array<string> | null;
  documentRelatedInfos?: Array<DocumentRelatedInfo> | null;
  dogInfo?: DogInfo;
  emailAddress?: string | null;
  givenName?: string | null;
  isDogTrainedByAccreditedSchool?: boolean | null;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName?: string | null;
  nonAccreditedSchoolQuestions?: NonAccreditedSchoolQuestions;
  phoneNumber?: string | null;
  serviceTypeCode?: ServiceTypeCode;
  surname?: string | null;
}
