/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GraduationInfo {
  accreditedSchoolId?: string | null;
  accreditedSchoolName?: string | null;
  schoolContactEmailAddress?: string | null;
  schoolContactGivenName?: string | null;
  schoolContactPhoneNumber?: string | null;
  schoolContactSurname?: string | null;
}
