/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum IdentityProviderTypeCode {
  BusinessBceId = 'BusinessBceId',
  BcServicesCard = 'BcServicesCard',
  Idir = 'Idir'
}
