/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LicenceFeeResponse } from '../models/licence-fee-response';
export interface LicenceFeeListResponse {
  licenceFees?: Array<LicenceFeeResponse> | null;
}
