/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceTypeCode } from '../models/service-type-code';
export interface MinistryResponse {
  id?: string;
  isActive?: boolean;
  name?: string | null;
  serviceTypeCodes?: Array<ServiceTypeCode> | null;
}
