/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrainingInfo } from '../models/training-info';
export interface NonAccreditedSchoolQuestions {
  areInoculationsUpToDate?: boolean | null;
  doctorIsProvidingNeedDogMedicalForm?: boolean | null;
  trainingInfo?: TrainingInfo;
}
