/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrgRegistrationStatusCode } from '../models/org-registration-status-code';
export interface OrgRegistrationPortalStatusResponse {
  status?: OrgRegistrationStatusCode;
}
