/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum OrgRegistrationStatusCode {
  ApplicationSubmitted = 'ApplicationSubmitted',
  InProgress = 'InProgress',
  CompleteSuccess = 'CompleteSuccess',
  CompleteFailed = 'CompleteFailed'
}
