/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OtherTraining {
  dogTrainerCredential?: string | null;
  hoursPracticingSkill?: string | null;
  trainerEmailAddress?: string | null;
  trainerGivenName?: string | null;
  trainerPhoneNumber?: string | null;
  trainerSurname?: string | null;
  trainingDetail?: string | null;
  trainingId?: string | null;
  trainingTime?: string | null;
  usePersonalDogTrainer?: boolean | null;
}
