/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum PaymentTypeCode {
  PayBcOnSubmission = 'PayBC_OnSubmission',
  Cash = 'Cash',
  CreditCard = 'CreditCard',
  MoneyOrder = 'MoneyOrder',
  Cheque = 'Cheque',
  CertifiedCheque = 'CertifiedCheque',
  CreditAccount = 'CreditAccount',
  JournalVoucher = 'JournalVoucher',
  NoPayment = 'NoPayment',
  PayBcSecurePaymentLink = 'PayBC_SecurePaymentLink'
}
