/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PrivateInvestigatorSwlContactInfo {
  bizContactId?: string | null;
  contactId?: string | null;
  emailAddress?: string | null;
  givenName?: string | null;
  licenceId?: string | null;
  middleName1?: string | null;
  middleName2?: string | null;
  phoneNumber?: string | null;
  surname?: string | null;
}
