/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ScreeningTypeCode {
  Staff = 'Staff',
  Contractor = 'Contractor',
  Licensee = 'Licensee'
}
