/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ServiceTypeCode {
  Psso = 'PSSO',
  CrrpEmployee = 'CRRP_EMPLOYEE',
  CrrpVolunteer = 'CRRP_VOLUNTEER',
  Mcfd = 'MCFD',
  PeCrc = 'PE_CRC',
  PeCrcVs = 'PE_CRC_VS',
  SecurityWorkerLicence = 'SecurityWorkerLicence',
  PssoVs = 'PSSO_VS',
  SecurityBusinessLicence = 'SecurityBusinessLicence',
  ArmouredVehiclePermit = 'ArmouredVehiclePermit',
  BodyArmourPermit = 'BodyArmourPermit',
  Mdra = 'MDRA',
  SecurityBusinessLicenceControllingMemberCrc = 'SECURITY_BUSINESS_LICENCE_CONTROLLING_MEMBER_CRC',
  GdsdTeamCertification = 'GDSDTeamCertification',
  DogTrainerCertification = 'DogTrainerCertification',
  RetiredServiceDogCertification = 'RetiredServiceDogCertification'
}
