/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailingAddress } from '../models/mailing-address';
export interface TrainingSchoolInfo {
  contactEmailAddress?: string | null;
  contactGivenName?: string | null;
  contactPhoneNumber?: string | null;
  contactSurname?: string | null;
  totalTrainingHours?: number | null;
  trainingBizMailingAddress?: MailingAddress;
  trainingBizName?: string | null;
  trainingEndDate?: string | null;
  trainingId?: string | null;
  trainingName?: string | null;
  trainingStartDate?: string | null;
  whatLearned?: string | null;
}
