/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkerLicenceCommandResponse {
  cost?: number | null;
  licenceAppId?: string | null;
}
