/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LicenceAppListResponse } from '../../models/licence-app-list-response';

export interface ApiApplicantsAnonymousDogCertificationApplicationsGet$Params {
}

export function apiApplicantsAnonymousDogCertificationApplicationsGet(http: HttpClient, rootUrl: string, params?: ApiApplicantsAnonymousDogCertificationApplicationsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LicenceAppListResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiApplicantsAnonymousDogCertificationApplicationsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LicenceAppListResponse>>;
    })
  );
}

apiApplicantsAnonymousDogCertificationApplicationsGet.PATH = '/api/applicants-anonymous/dog-certification-applications';
