{{- if .Values.clamav.db.persistent -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clamav.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.clamav.db.size }}
{{- end -}}