apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clamav.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.clamav.replicaCount }}
  selector:
    matchLabels:
      {{- include "clamav.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "clamav.selectorLabels" . | nindent 8 }}
        DataClass: Low
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: clamav
        image: "{{ .Values.clamav.image }}:{{ default .Chart.AppVersion .Values.clamav.tag }}"
        command: [/init-unprivileged]
        imagePullPolicy: "{{ .Values.clamav.imagePullPolicy }}"
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: 3310
          name: clamav
          protocol: TCP
        # Give clamav up to 300s to get CVDs in place etc.
        startupProbe:
          exec:
            command:
            - clamdcheck.sh
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - clamdcheck.sh
          failureThreshold: 2
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.clamav.resources | nindent 10 }}
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: db
          - mountPath: /etc/logs/clamav
            name: logs
          # clamd.conf file
          - mountPath: /etc/clamav/clamd.conf
            name: config-volume
            readOnly: true
            subPath: clamd.conf
          # freshclam.conf file
          - mountPath: /etc/clamav/freshclam.conf
            name: config-volume
            readOnly: true
            subPath: freshclam.conf
        env:
          - name: HTTP_PROXY
            value: http://swpxkam.gov.bc.ca:8080
          - name: HTTPS_PROXY
            value: http://swpxkam.gov.bc.ca:8080
          - name: NO_PROXY
            value: .cluster.local,.svc,10.91.0.0/16,172.30.0.0/16,142.34.0.0/16,127.0.0.1,localhost,.gov.bc.ca,.bceid.ca
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "clamav.fullname" . }}
      - name: db
        {{- if .Values.clamav.db.persistent }}
        persistentVolumeClaim:
          claimName: {{ include "clamav.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: logs
        emptyDir: {}
      {{- with .Values.clamav.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Prevent clamav pods running in same host.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  {{- include "clamav.selectorLabels" . | nindent 18 }} 
      {{- with .Values.clamav.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
