apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: prod-release-pipeline
  labels:
    DataClass: Low
spec:
  tasks:

   ## Promote staging to prod ##
    - name: prod-screening-portal
      params:
        - name: imageName
          value: screening-portal
        - name: fromTag
          value: staging
        - name: toTag
          value: prod
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: promote-image-task

    - name: prod-licensing-portal
      params:
        - name: imageName
          value: licensing-portal
        - name: fromTag
          value: staging
        - name: toTag
          value: prod
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: promote-image-task

    - name: prod-dynamics-helper
      params:
        - name: imageName
          value: dynamics-helper
        - name: fromTag
          value: staging
        - name: toTag
          value: prod
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: promote-image-task

    - name: prod-job-scheduler
      params:
        - name: imageName
          value: jag-jobscheduler
        - name: fromTag
          value: staging
        - name: toTag
          value: prod
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: promote-image-task