apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-release-pipeline
  labels:
    DataClass: Low

spec:
  params:
    - name: imageTag
      description: "GHCR source tag imported into the test ImageStream"
      default: "test"
    - name: promoteScreening
      description: ""
      default: "true"
    - name: promoteLicensing
      description: ""
      default: "true"
    - name: promoteDynamicsHelper
      description: ""
      default: "true"
    - name: promoteGDSD
      description: ""
      default: "true"

  tasks:
    ## Import ghcr :test into the test ImageStream ##
    - name: test-screening-portal
      when:
        - input: "$(params.promoteScreening)"
          operator: in
          values: ["true"]
      params:
        - name: sourceImage
          value: ghcr.io/bcgov/pssg-spdbt/screening-portal
        - name: sourceTag
          value: $(params.imageTag)
        - name: destinationImage
          value: screening-portal
        - name: destinationTag
          value: test
        - name: scheduled
          value: false
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: tag-image-task

    - name: test-licensing-portal
      when:
        - input: "$(params.promoteLicensing)"
          operator: in
          values: ["true"]
      params:
        - name: sourceImage
          value: ghcr.io/bcgov/pssg-spdbt/licensing-portal
        - name: sourceTag
          value: $(params.imageTag)
        - name: destinationImage
          value: licensing-portal
        - name: destinationTag
          value: test
        - name: scheduled
          value: false
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: tag-image-task

    - name: test-dynamics-helper
      when:
        - input: "$(params.promoteDynamicsHelper)"
          operator: in
          values: ["true"]
      params:
        - name: sourceImage
          value: ghcr.io/bcgov/pssg-spdbt/dynamics-helper
        - name: sourceTag
          value: $(params.imageTag)
        - name: destinationImage
          value: dynamics-helper
        - name: destinationTag
          value: test
        - name: scheduled
          value: false
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: tag-image-task

    - name: test-gdsd-portal
      when:
        - input: "$(params.promoteGDSD)"
          operator: in
          values: ["true"]
      params:
        - name: sourceImage
          value: ghcr.io/bcgov/pssg-spdbt/gdsd-portal
        - name: sourceTag
          value: $(params.imageTag)
        - name: destinationImage
          value: gdsd-portal
        - name: destinationTag
          value: test
        - name: scheduled
          value: false
        - name: referencePolicy
          value: local
      taskRef:
        kind: Task
        name: tag-image-task
