apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: zap-scan
spec:
  workspaces:
    - name: owasp-settings
      description: |
        mounts /zap/wrk to store generated configs and results.

  tasks:
    - name: zap-scan-screening-portal
      taskRef:
        kind: Task
        name: zap-scan-task
      params:
        - name: TARGET_URL
          value: https://dev-spd-screening-portal.apps.emerald.devops.gov.bc.ca/
        - name: SCAN_TYPE
          value: full
        - name: SCAN_DURATION
          value: 10
      workspaces:
        - name: owasp-settings
          workspace: owasp-settings
    - name: zap-scan-screening-portal-api
      taskRef:
        kind: Task
        name: zap-scan-task
      params:
        - name: TARGET_URL
          value: https://dev-spd-licensing-portal.apps.emerald.devops.gov.bc.ca/swagger/v1/swagger.json
        - name: SCAN_TYPE
          value: api
      workspaces:
        - name: owasp-settings
          workspace: owasp-settings