/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GdsdTeamLicenceAppResponse } from '../../models/gdsd-team-licence-app-response';

export interface ApiGdsdTeamAppLicenceAppIdGet$Params {
  licenceAppId: string;
}

export function apiGdsdTeamAppLicenceAppIdGet(http: HttpClient, rootUrl: string, params: ApiGdsdTeamAppLicenceAppIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<GdsdTeamLicenceAppResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGdsdTeamAppLicenceAppIdGet.PATH, 'get');
  if (params) {
    rb.path('licenceAppId', params.licenceAppId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GdsdTeamLicenceAppResponse>;
    })
  );
}

apiGdsdTeamAppLicenceAppIdGet.PATH = '/api/gdsd-team-app/{licenceAppId}';
