/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RetiredDogLicenceAppResponse } from '../../models/retired-dog-licence-app-response';

export interface ApiRetiredDogAppLicenceAppIdGet$Params {
  licenceAppId: string;
}

export function apiRetiredDogAppLicenceAppIdGet(http: HttpClient, rootUrl: string, params: ApiRetiredDogAppLicenceAppIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<RetiredDogLicenceAppResponse>> {
  const rb = new RequestBuilder(rootUrl, apiRetiredDogAppLicenceAppIdGet.PATH, 'get');
  if (params) {
    rb.path('licenceAppId', params.licenceAppId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RetiredDogLicenceAppResponse>;
    })
  );
}

apiRetiredDogAppLicenceAppIdGet.PATH = '/api/retired-dog-app/{licenceAppId}';
