/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RetiredDogAppCommandResponse } from '../../models/retired-dog-app-command-response';
import { RetiredDogLicenceAppUpsertRequest } from '../../models/retired-dog-licence-app-upsert-request';

export interface ApiRetiredDogAppPost$Params {
      body: RetiredDogLicenceAppUpsertRequest
}

export function apiRetiredDogAppPost(http: HttpClient, rootUrl: string, params: ApiRetiredDogAppPost$Params, context?: HttpContext): Observable<StrictHttpResponse<RetiredDogAppCommandResponse>> {
  const rb = new RequestBuilder(rootUrl, apiRetiredDogAppPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RetiredDogAppCommandResponse>;
    })
  );
}

apiRetiredDogAppPost.PATH = '/api/retired-dog-app';
