/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAccreditedDogSchoolsGet } from '../fn/dog-school/api-accredited-dog-schools-get';
import { ApiAccreditedDogSchoolsGet$Params } from '../fn/dog-school/api-accredited-dog-schools-get';
import { DogSchoolResponse } from '../models/dog-school-response';

@Injectable({ providedIn: 'root' })
export class DogSchoolService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAccreditedDogSchoolsGet()` */
  static readonly ApiAccreditedDogSchoolsGetPath = '/api/accredited-dog-schools';

  /**
   * Get accredited dog Schools.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAccreditedDogSchoolsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAccreditedDogSchoolsGet$Response(params?: ApiAccreditedDogSchoolsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DogSchoolResponse>>> {
    return apiAccreditedDogSchoolsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get accredited dog Schools.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAccreditedDogSchoolsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAccreditedDogSchoolsGet(params?: ApiAccreditedDogSchoolsGet$Params, context?: HttpContext): Observable<Array<DogSchoolResponse>> {
    return this.apiAccreditedDogSchoolsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DogSchoolResponse>>): Array<DogSchoolResponse> => r.body)
    );
  }

}
