/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ActionResult } from '../models/action-result';
import { apiApplicantApplicantIdTermAgreeGet } from '../fn/login/api-applicant-applicant-id-term-agree-get';
import { ApiApplicantApplicantIdTermAgreeGet$Params } from '../fn/login/api-applicant-applicant-id-term-agree-get';
import { apiApplicantLoginGet } from '../fn/login/api-applicant-login-get';
import { ApiApplicantLoginGet$Params } from '../fn/login/api-applicant-login-get';
import { ApplicantLoginResponse } from '../models/applicant-login-response';

@Injectable({ providedIn: 'root' })
export class LoginService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiApplicantLoginGet()` */
  static readonly ApiApplicantLoginGetPath = '/api/applicant/login';

  /**
   * login, for swl/permit portal, bc service card login.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiApplicantLoginGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiApplicantLoginGet$Response(params?: ApiApplicantLoginGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicantLoginResponse>> {
    return apiApplicantLoginGet(this.http, this.rootUrl, params, context);
  }

  /**
   * login, for swl/permit portal, bc service card login.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiApplicantLoginGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiApplicantLoginGet(params?: ApiApplicantLoginGet$Params, context?: HttpContext): Observable<ApplicantLoginResponse> {
    return this.apiApplicantLoginGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApplicantLoginResponse>): ApplicantLoginResponse => r.body)
    );
  }

  /** Path part for operation `apiApplicantApplicantIdTermAgreeGet()` */
  static readonly ApiApplicantApplicantIdTermAgreeGetPath = '/api/applicant/{applicantId}/term-agree';

  /**
   * when user select agree to the Term. Call this endpoint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiApplicantApplicantIdTermAgreeGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiApplicantApplicantIdTermAgreeGet$Response(params: ApiApplicantApplicantIdTermAgreeGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ActionResult>> {
    return apiApplicantApplicantIdTermAgreeGet(this.http, this.rootUrl, params, context);
  }

  /**
   * when user select agree to the Term. Call this endpoint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiApplicantApplicantIdTermAgreeGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiApplicantApplicantIdTermAgreeGet(params: ApiApplicantApplicantIdTermAgreeGet$Params, context?: HttpContext): Observable<ActionResult> {
    return this.apiApplicantApplicantIdTermAgreeGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<ActionResult>): ActionResult => r.body)
    );
  }

}
