/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiApplicantsApplicantIdSwlLatestGet } from '../fn/security-worker-licensing/api-applicants-applicant-id-swl-latest-get';
import { ApiApplicantsApplicantIdSwlLatestGet$Params } from '../fn/security-worker-licensing/api-applicants-applicant-id-swl-latest-get';
import { apiSpWorkerLicenceApplicationGet } from '../fn/security-worker-licensing/api-sp-worker-licence-application-get';
import { ApiSpWorkerLicenceApplicationGet$Params } from '../fn/security-worker-licensing/api-sp-worker-licence-application-get';
import { apiWorkerLicenceApplicationGet } from '../fn/security-worker-licensing/api-worker-licence-application-get';
import { ApiWorkerLicenceApplicationGet$Params } from '../fn/security-worker-licensing/api-worker-licence-application-get';
import { apiWorkerLicenceApplicationsAnonymousSubmitPost } from '../fn/security-worker-licensing/api-worker-licence-applications-anonymous-submit-post';
import { ApiWorkerLicenceApplicationsAnonymousSubmitPost$Params } from '../fn/security-worker-licensing/api-worker-licence-applications-anonymous-submit-post';
import { apiWorkerLicenceApplicationsAuthenticatedSubmitPost } from '../fn/security-worker-licensing/api-worker-licence-applications-authenticated-submit-post';
import { ApiWorkerLicenceApplicationsAuthenticatedSubmitPost$Params } from '../fn/security-worker-licensing/api-worker-licence-applications-authenticated-submit-post';
import { apiWorkerLicenceApplicationsLicenceAppIdGet } from '../fn/security-worker-licensing/api-worker-licence-applications-licence-app-id-get';
import { ApiWorkerLicenceApplicationsLicenceAppIdGet$Params } from '../fn/security-worker-licensing/api-worker-licence-applications-licence-app-id-get';
import { apiWorkerLicenceApplicationsPost } from '../fn/security-worker-licensing/api-worker-licence-applications-post';
import { ApiWorkerLicenceApplicationsPost$Params } from '../fn/security-worker-licensing/api-worker-licence-applications-post';
import { apiWorkerLicenceApplicationsSubmitPost } from '../fn/security-worker-licensing/api-worker-licence-applications-submit-post';
import { ApiWorkerLicenceApplicationsSubmitPost$Params } from '../fn/security-worker-licensing/api-worker-licence-applications-submit-post';
import { WorkerLicenceAppResponse } from '../models/worker-licence-app-response';
import { WorkerLicenceCommandResponse } from '../models/worker-licence-command-response';

@Injectable({ providedIn: 'root' })
export class SecurityWorkerLicensingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiWorkerLicenceApplicationsPost()` */
  static readonly ApiWorkerLicenceApplicationsPostPath = '/api/worker-licence-applications';

  /**
   * Create Security Worker Licence Application, the DocumentInfos under WorkerLicenceAppUpsertRequest should contain all documents this application needs. If the document
   * is not needed for this application, then remove it from documentInfos.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkerLicenceApplicationsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsPost$Response(params: ApiWorkerLicenceApplicationsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceCommandResponse>> {
    return apiWorkerLicenceApplicationsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create Security Worker Licence Application, the DocumentInfos under WorkerLicenceAppUpsertRequest should contain all documents this application needs. If the document
   * is not needed for this application, then remove it from documentInfos.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkerLicenceApplicationsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsPost(params: ApiWorkerLicenceApplicationsPost$Params, context?: HttpContext): Observable<WorkerLicenceCommandResponse> {
    return this.apiWorkerLicenceApplicationsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceCommandResponse>): WorkerLicenceCommandResponse => r.body)
    );
  }

  /** Path part for operation `apiWorkerLicenceApplicationsLicenceAppIdGet()` */
  static readonly ApiWorkerLicenceApplicationsLicenceAppIdGetPath = '/api/worker-licence-applications/{licenceAppId}';

  /**
   * Get Security Worker Licence Application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkerLicenceApplicationsLicenceAppIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkerLicenceApplicationsLicenceAppIdGet$Response(params: ApiWorkerLicenceApplicationsLicenceAppIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceAppResponse>> {
    return apiWorkerLicenceApplicationsLicenceAppIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Security Worker Licence Application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkerLicenceApplicationsLicenceAppIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkerLicenceApplicationsLicenceAppIdGet(params: ApiWorkerLicenceApplicationsLicenceAppIdGet$Params, context?: HttpContext): Observable<WorkerLicenceAppResponse> {
    return this.apiWorkerLicenceApplicationsLicenceAppIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceAppResponse>): WorkerLicenceAppResponse => r.body)
    );
  }

  /** Path part for operation `apiApplicantsApplicantIdSwlLatestGet()` */
  static readonly ApiApplicantsApplicantIdSwlLatestGetPath = '/api/applicants/{applicantId}/swl-latest';

  /**
   * Get Lastest Security Worker Licence Application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiApplicantsApplicantIdSwlLatestGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiApplicantsApplicantIdSwlLatestGet$Response(params: ApiApplicantsApplicantIdSwlLatestGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceAppResponse>> {
    return apiApplicantsApplicantIdSwlLatestGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Lastest Security Worker Licence Application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiApplicantsApplicantIdSwlLatestGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiApplicantsApplicantIdSwlLatestGet(params: ApiApplicantsApplicantIdSwlLatestGet$Params, context?: HttpContext): Observable<WorkerLicenceAppResponse> {
    return this.apiApplicantsApplicantIdSwlLatestGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceAppResponse>): WorkerLicenceAppResponse => r.body)
    );
  }

  /** Path part for operation `apiWorkerLicenceApplicationsSubmitPost()` */
  static readonly ApiWorkerLicenceApplicationsSubmitPostPath = '/api/worker-licence-applications/submit';

  /**
   * Submit Security Worker Licence Application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkerLicenceApplicationsSubmitPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsSubmitPost$Response(params: ApiWorkerLicenceApplicationsSubmitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceCommandResponse>> {
    return apiWorkerLicenceApplicationsSubmitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit Security Worker Licence Application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkerLicenceApplicationsSubmitPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsSubmitPost(params: ApiWorkerLicenceApplicationsSubmitPost$Params, context?: HttpContext): Observable<WorkerLicenceCommandResponse> {
    return this.apiWorkerLicenceApplicationsSubmitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceCommandResponse>): WorkerLicenceCommandResponse => r.body)
    );
  }

  /** Path part for operation `apiWorkerLicenceApplicationsAuthenticatedSubmitPost()` */
  static readonly ApiWorkerLicenceApplicationsAuthenticatedSubmitPostPath = '/api/worker-licence-applications/authenticated/submit';

  /**
   * Submit Security Worker Licence Application Json part for authenticated users, supports only: renewal, update and replace
   * After fe done with the uploading files, then fe do post with json payload, inside payload, it needs to contain an array of keycode for the files.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkerLicenceApplicationsAuthenticatedSubmitPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsAuthenticatedSubmitPost$Response(params?: ApiWorkerLicenceApplicationsAuthenticatedSubmitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceCommandResponse>> {
    return apiWorkerLicenceApplicationsAuthenticatedSubmitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit Security Worker Licence Application Json part for authenticated users, supports only: renewal, update and replace
   * After fe done with the uploading files, then fe do post with json payload, inside payload, it needs to contain an array of keycode for the files.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkerLicenceApplicationsAuthenticatedSubmitPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsAuthenticatedSubmitPost(params?: ApiWorkerLicenceApplicationsAuthenticatedSubmitPost$Params, context?: HttpContext): Observable<WorkerLicenceCommandResponse> {
    return this.apiWorkerLicenceApplicationsAuthenticatedSubmitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceCommandResponse>): WorkerLicenceCommandResponse => r.body)
    );
  }

  /** Path part for operation `apiWorkerLicenceApplicationGet()` */
  static readonly ApiWorkerLicenceApplicationGetPath = '/api/worker-licence-application';

  /**
   * Get Security Worker Licence Application, anonymous one, so, we get the licenceAppId from cookies.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkerLicenceApplicationGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkerLicenceApplicationGet$Response(params?: ApiWorkerLicenceApplicationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceAppResponse>> {
    return apiWorkerLicenceApplicationGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Security Worker Licence Application, anonymous one, so, we get the licenceAppId from cookies.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkerLicenceApplicationGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkerLicenceApplicationGet(params?: ApiWorkerLicenceApplicationGet$Params, context?: HttpContext): Observable<WorkerLicenceAppResponse> {
    return this.apiWorkerLicenceApplicationGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceAppResponse>): WorkerLicenceAppResponse => r.body)
    );
  }

  /** Path part for operation `apiSpWorkerLicenceApplicationGet()` */
  static readonly ApiSpWorkerLicenceApplicationGetPath = '/api/sp-worker-licence-application';

  /**
   * Get Security Worker Licence SoleProprietor Application, anonymous one, so, we get the swlAppId from cookies.
   * Used for sole proprietor, biz app is aborted, fe needs to get the swl application.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSpWorkerLicenceApplicationGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSpWorkerLicenceApplicationGet$Response(params?: ApiSpWorkerLicenceApplicationGet$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceAppResponse>> {
    return apiSpWorkerLicenceApplicationGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get Security Worker Licence SoleProprietor Application, anonymous one, so, we get the swlAppId from cookies.
   * Used for sole proprietor, biz app is aborted, fe needs to get the swl application.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSpWorkerLicenceApplicationGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSpWorkerLicenceApplicationGet(params?: ApiSpWorkerLicenceApplicationGet$Params, context?: HttpContext): Observable<WorkerLicenceAppResponse> {
    return this.apiSpWorkerLicenceApplicationGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceAppResponse>): WorkerLicenceAppResponse => r.body)
    );
  }

  /** Path part for operation `apiWorkerLicenceApplicationsAnonymousSubmitPost()` */
  static readonly ApiWorkerLicenceApplicationsAnonymousSubmitPostPath = '/api/worker-licence-applications/anonymous/submit';

  /**
   * Submit Security Worker Licence Application Json part Anonymously
   * After fe done with the uploading files, then fe do post with json payload, inside payload, it needs to contain an array of keycode for the files.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkerLicenceApplicationsAnonymousSubmitPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsAnonymousSubmitPost$Response(params?: ApiWorkerLicenceApplicationsAnonymousSubmitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkerLicenceCommandResponse>> {
    return apiWorkerLicenceApplicationsAnonymousSubmitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit Security Worker Licence Application Json part Anonymously
   * After fe done with the uploading files, then fe do post with json payload, inside payload, it needs to contain an array of keycode for the files.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkerLicenceApplicationsAnonymousSubmitPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkerLicenceApplicationsAnonymousSubmitPost(params?: ApiWorkerLicenceApplicationsAnonymousSubmitPost$Params, context?: HttpContext): Observable<WorkerLicenceCommandResponse> {
    return this.apiWorkerLicenceApplicationsAnonymousSubmitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<WorkerLicenceCommandResponse>): WorkerLicenceCommandResponse => r.body)
    );
  }

}
