/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IActionResult } from '../../models/i-action-result';

export interface ApiBizMergeOldBizIdNewBizIdGet$Params {
  oldBizId: string;
  newBizId: string;
}

export function apiBizMergeOldBizIdNewBizIdGet(http: HttpClient, rootUrl: string, params: ApiBizMergeOldBizIdNewBizIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<IActionResult>> {
  const rb = new RequestBuilder(rootUrl, apiBizMergeOldBizIdNewBizIdGet.PATH, 'get');
  if (params) {
    rb.path('oldBizId', params.oldBizId, {});
    rb.path('newBizId', params.newBizId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IActionResult>;
    })
  );
}

apiBizMergeOldBizIdNewBizIdGet.PATH = '/api/biz/merge/{oldBizId}/{newBizId}';
