/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BizMemberResponse } from '../../models/biz-member-response';
import { NonSwlContactInfo } from '../../models/non-swl-contact-info';

export interface ApiBusinessBizIdNonSwlBusinessManagersBizContactIdPut$Params {
  bizId: string;
  bizContactId: string;
      body?: NonSwlContactInfo
}

export function apiBusinessBizIdNonSwlBusinessManagersBizContactIdPut(http: HttpClient, rootUrl: string, params: ApiBusinessBizIdNonSwlBusinessManagersBizContactIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<BizMemberResponse>> {
  const rb = new RequestBuilder(rootUrl, apiBusinessBizIdNonSwlBusinessManagersBizContactIdPut.PATH, 'put');
  if (params) {
    rb.path('bizId', params.bizId, {});
    rb.path('bizContactId', params.bizContactId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BizMemberResponse>;
    })
  );
}

apiBusinessBizIdNonSwlBusinessManagersBizContactIdPut.PATH = '/api/business/{bizId}/non-swl-business-managers/{bizContactId}';
