/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StakeholderAppInviteVerifyRequest } from '../../models/stakeholder-app-invite-verify-request';
import { StakeholderAppInviteVerifyResponse } from '../../models/stakeholder-app-invite-verify-response';

export interface ApiStakeholdersInvitesPost$Params {
      body: StakeholderAppInviteVerifyRequest
}

export function apiStakeholdersInvitesPost(http: HttpClient, rootUrl: string, params: ApiStakeholdersInvitesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<StakeholderAppInviteVerifyResponse>> {
  const rb = new RequestBuilder(rootUrl, apiStakeholdersInvitesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StakeholderAppInviteVerifyResponse>;
    })
  );
}

apiStakeholdersInvitesPost.PATH = '/api/stakeholders/invites';
