version: "3"

services:
  backend:
    image: spd-backend
    working_dir: /app
    environment:
      ENABLE_SWAGGER: "true"
      ASPNETCORE_URLS: http://+:80    
    ports:
      - "${IP:-0.0.0.0}:8484:80"
    networks:
      - spd_it


  backend-dev:
    image: spd-backend-dev
    working_dir: /app
    environment:
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: "true"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "${IP:-0.0.0.0}:8384:80"
    networks:
      - spd_it
    entrypoint: /bin/bash
    command:
      [
        "-c",
        'echo "Waiting for db ..."; sleep 15; echo "Starting backend service..."; dotnet watch run --project=./Rsvp.Cms.Api/Rsvp.Cms.Api.csproj'
      ]

  frontend:
    image: spd-frontend
    environment:
      WEB_HOST_NAME: http://localhost
      WEB_HOST_PORT: 5200
      API_HOST: backend
      API_PORT: 80
    volumes:
      - ./frontend/config/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/config/config.json:/srv/assets/config/config.json
    ports:
      - 5200:5200
    networks:
      - spd_it

  frontend-dev:
    image: node:fermium
    working_dir: /frontend
    volumes:
      - ../frontend:/frontend
      - frontend-npm-cache:/frontend/node_modules
    ports:
      - 4200:4200
    networks:
      - spd_it
    entrypoint: /bin/bash
    command: [ "-c", "npm install --no-save; npm start" ]

volumes:
  frontend-npm-cache:

networks:
  spd_it:
