/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationInviteStatusCode } from '../models/application-invite-status-code';
import { PayerPreferenceTypeCode } from '../models/payer-preference-type-code';
export interface ApplicationInviteResponse {
  createdOn?: string;
  email?: string | null;
  errorMsg?: string | null;
  firstName?: string | null;
  id?: string;
  jobTitle?: string | null;
  lastName?: string | null;
  orgId?: string;
  payeeType?: PayerPreferenceTypeCode;
  status?: ApplicationInviteStatusCode;
  viewed?: boolean | null;
}
