/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationInviteResponse } from '../models/application-invite-response';
import { PaginationResponse } from '../models/pagination-response';
export interface ApplicationInviteListResponse {
  applicationInvites?: Array<ApplicationInviteResponse> | null;
  pagination?: PaginationResponse;
}
