/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicantAppFileCreateResponse {
  applicationId?: string | null;
  documentUrlId?: string;
  uploadedDateTime?: string;
}
