/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationInviteDuplicateResponse } from '../models/application-invite-duplicate-response';
export interface ApplicationInvitesCreateResponse {
  createSuccess?: boolean;
  duplicateResponses?: Array<ApplicationInviteDuplicateResponse> | null;
  errorReason?: string | null;
  isDuplicateCheckRequired?: boolean;
  orgId?: string;
}
