/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileTypeCode } from '../models/file-type-code';
export interface ApplicantApplicationFileResponse {
  fileName?: string | null;
  fileTypeCode?: FileTypeCode;
  uploadedDateTime?: string;
}
