/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationResponse } from '../models/application-response';
import { PaginationResponse } from '../models/pagination-response';
export interface ApplicationListResponse {
  applications?: Array<ApplicationResponse> | null;
  pagination?: PaginationResponse;
}
