/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BulkHistoryResponse } from '../models/bulk-history-response';
import { PaginationResponse } from '../models/pagination-response';
export interface BulkHistoryListResponse {
  bulkUploadHistorys?: Array<BulkHistoryResponse> | null;
  pagination?: PaginationResponse;
}
