/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkHistoryResponse {
  batchNumber?: string | null;
  fileName?: string | null;
  id?: string;
  uploadedByUserFullName?: string | null;
  uploadedDateTime?: string;
}
