/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationCreateResult } from '../models/application-create-result';
import { BulkAppsCreateResultCode } from '../models/bulk-apps-create-result-code';
export interface BulkAppsCreateResponse {
  bulkAppsCreateCode?: BulkAppsCreateResultCode;
  createAppResults?: Array<ApplicationCreateResult> | null;
}
