/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DelegateCreateRequest {
  emailAddress?: string | null;
  firstName?: string | null;
  lastName?: string | null;
}
