/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PssoUserRoleEnum } from '../models/psso-user-role-enum';
export interface DelegateResponse {
  emailAddress?: string | null;
  firstName?: string | null;
  id?: string;
  lastName?: string | null;
  portalUserId?: string | null;
  pssoUserRoleCode?: PssoUserRoleEnum;
}
