/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DelegateResponse } from '../models/delegate-response';
export interface DelegateListResponse {
  delegates?: Array<DelegateResponse> | null;
}
