/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum EmployeeOrganizationTypeCode {
  Childcare = 'Childcare',
  Healthcare = 'Healthcare',
  Education = 'Education',
  Funding = 'Funding',
  CrownCorp = 'CrownCorp',
  ProvGovt = 'ProvGovt',
  Registrant = 'Registrant',
  GovnBody = 'GovnBody',
  Appointed = 'Appointed'
}
