/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrgUserResponse } from '../models/org-user-response';
export interface OrgUserListResponse {
  maximumNumberOfAuthorizedContacts?: number | null;
  maximumNumberOfPrimaryAuthorizedContacts?: number | null;
  users?: Array<OrgUserResponse> | null;
}
