/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrgReportResponse } from '../models/org-report-response';
export interface OrgReportListResponse {
  reports?: Array<OrgReportResponse> | null;
}
