/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMethodCode } from '../models/payment-method-code';
export interface PaymentLinkCreateRequest {
  applicationId?: string | null;
  paymentMethod?: PaymentMethodCode;
}
