/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ShareableClearanceItem } from '../models/shareable-clearance-item';
export interface ShareableClearanceResponse {
  items?: Array<ShareableClearanceItem> | null;
}
