/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ServiceTypeCode } from '../models/service-type-code';
export interface ShareableClearanceItem {
  clearanceId?: string;
  expiryDate?: string | null;
  grantedDate?: string | null;
  orgId?: string;
  serviceType?: ServiceTypeCode;
}
