/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum UserInfoMsgTypeCode {
  RegistrationDenied = 'REGISTRATION_DENIED',
  AccountNotMatchRecord = 'ACCOUNT_NOT_MATCH_RECORD',
  NoActiveAccountForOrg = 'NO_ACTIVE_ACCOUNT_FOR_ORG'
}
