/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum VolunteerOrganizationTypeCode {
  Registrant = 'Registrant',
  NonProfit = 'NonProfit',
  Childcare = 'Childcare',
  Healthcare = 'Healthcare',
  Education = 'Education',
  ProvFunded = 'ProvFunded',
  CrownCorp = 'CrownCorp',
  ProvGovt = 'ProvGovt',
  Municipality = 'Municipality',
  PostSec = 'PostSec'
}
