using System.Text.Json;
using System.Text.Json.Serialization;

namespace Spd.Utilities.Printing.BCMailPlus;

/// <summary>
/// BCMailPlus Sdk
/// </summary>
public interface IBcMailPlusApi
{
    /// <summary>
    /// Creates a new job
    /// </summary>
    /// <param name="jobClass">The job class</param>
    /// <param name="payload">The payload for the job</param>
    /// <param name="ct">A cancellation token</param>
    /// <returns>A job status instance</returns>
    Task<JobStatus> CreateJob(string jobClass, JsonDocument payload, CancellationToken ct);

    /// <summary>
    /// Gets job statuses
    /// </summary>
    /// <param name="jobs">The job ids to get statuses for</param>
    /// <param name="ct">A cancellation token</param>
    /// <returns>Array of job status responses</returns>
    Task<IEnumerable<JobStatus>> GetJobStatus(IEnumerable<string> jobs, CancellationToken ct);

    /// <summary>
    /// Gets a digital asset from a job
    /// </summary>
    /// <param name="jobId">The job id</param>
    /// <param name="asset">The asset name</param>
    /// <param name="ct">A cancellation token</param>
    /// <returns>Byte array representing the asset, null if not found</returns>
    Task<byte[]?> GetAsset(string jobId, string asset, CancellationToken ct);
}

/// <summary>
/// BCMailPlus job status response
/// </summary>
public class JobStatus
{
    /// <summary>
    /// Job status that indicates success
    /// </summary>
    public const string PdfCreated = "PDF_CREATED";

    /// <summary>
    /// Job status that indicates errors
    /// </summary>
    public const string ProcessingError = "PROCESSING_ERROR";

    /// <summary>
    /// The job id
    /// </summary>
    public string? JobId { get; set; }

    /// <summary>
    /// The job status
    /// </summary>
    [JsonPropertyName("jobStatus")]
    public string? Status { get; set; }

    /// <summary>
    /// Any errors related to the job
    /// </summary>
    public string? Errors { get; set; }

    /// <summary>
    /// Various job properties
    /// </summary>
    public JobProperties? JobProperties { get; set; }
}

/// <summary>
/// BCMailPlus job properties
/// </summary>
public class JobProperties
{
    /// <summary>
    /// BCMailPlus internal job id
    /// </summary>
    [JsonPropertyName("JOB_ID")]
    public int? JobId { get; set; }

    /// <summary>
    /// The Asset name generated by the job
    /// </summary>
    [JsonPropertyName("ASSET")]
    public string? Asset { get; set; }
}