/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DogSchoolResponse } from '../../models/dog-school-response';

export interface ApiAccreditedDogSchoolsGet$Params {
}

export function apiAccreditedDogSchoolsGet(http: HttpClient, rootUrl: string, params?: ApiAccreditedDogSchoolsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DogSchoolResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiAccreditedDogSchoolsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DogSchoolResponse>>;
    })
  );
}

apiAccreditedDogSchoolsGet.PATH = '/api/accredited-dog-schools';
