/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GdsdTeamAppCommandResponse } from '../../models/gdsd-team-app-command-response';
import { GdsdTeamLicenceAppChangeRequest } from '../../models/gdsd-team-licence-app-change-request';

export interface ApiGdsdTeamAppChangePost$Params {
  
    /**
     * GDSDTeamLicenceAppChangeRequest data
     */
    body?: GdsdTeamLicenceAppChangeRequest
}

export function apiGdsdTeamAppChangePost(http: HttpClient, rootUrl: string, params?: ApiGdsdTeamAppChangePost$Params, context?: HttpContext): Observable<StrictHttpResponse<GdsdTeamAppCommandResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGdsdTeamAppChangePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GdsdTeamAppCommandResponse>;
    })
  );
}

apiGdsdTeamAppChangePost.PATH = '/api/gdsd-team-app/change';
