using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Spd.Manager.Cases.Payment;
using Spd.Utilities.Shared;
using System.Configuration;

namespace Spd.Presentation.Dynamics.Controllers;

/// <summary>
/// Payment support for dynamics
/// </summary>
[Authorize]
public class PaymentController : SpdControllerBase
{
    private readonly IMediator _mediator;
    private readonly IConfiguration _configuration;

    public PaymentController(IMediator mediator, IConfiguration configuration) : base()
    {
        _mediator = mediator;
        _configuration = configuration;
    }

    /// <summary>
    /// Get a pre payment link
    /// </summary>
    /// <param name="applicationId">the GUID of the screening application</param>
    /// <param name="ct">cancellation token, generated by dotnetcore</param>
    /// <response code="200">Ok, with the correct link generated</response>
    /// <response code="403">if the application cannot be found</response>
    /// <returns>
    /// </returns>
    [HttpGet]
    [Route("api/pre-payment-link/{applicationId}")]
    public async Task<PrePaymentLinkResponse> GetPrePaymentLinkAsync(
        [FromRoute] Guid applicationId,
        CancellationToken ct)
    {
        string? screeningHostUrl = _configuration.GetValue<string>("ScreeningHostUrl");
        string? screeningPaymentPath = _configuration.GetValue<string>("ScreeningAppPaymentPath");
        if (screeningHostUrl == null || screeningPaymentPath == null)
        {
            throw new ConfigurationErrorsException("ScreeningHostUrl or screeningPaymentPath is not set correctly.");
        }
        return await _mediator.Send(new PrePaymentLinkCreateCommand(applicationId, $"{screeningHostUrl}{screeningPaymentPath}"), ct);

    }

    /// <summary>
    /// Payment refund
    /// </summary>
    /// <param name="paymentId">the GUID of the payment</param>
    /// <param name="ct">cancellation token, generated by dotnetcore</param>
    /// <response code="200">Ok, refund request processed</response>
    /// <response code="403">if the payment cannot be found or payment is in wrong status</response>
    /// <returns>
    /// </returns>
    [HttpGet]
    [Route("api/payment/{paymentId}/refund")]
    public async Task<PaymentRefundResponse> RefundPaymentAsync(
        [FromRoute] Guid paymentId,
        CancellationToken ct)
    {
        return await _mediator.Send(new PaymentRefundCommand(paymentId), ct);
    }

    /// <summary>
    /// Payment create invoices
    /// </summary>
    /// <param name="paymentId">the GUID of the payment</param>
    /// <param name="ct">cancellation token, generated by dotnetcore</param>
    /// <response code="200">Ok,create invoices request processed</response>
    /// <returns>
    /// </returns>
    [HttpPost]
    [Route("api/payment/invoices")]
    public async Task<CreateInvoicesInCasResponse> CreateInvoiceInCasAsync(CancellationToken ct)
    {
        return await _mediator.Send(new CreateInvoicesInCasCommand(), ct);
    }
}
