import {
	ApplicationPortalStatusCode,
	CaseSubStatusCode,
	ContactAuthorizationTypeCode,
	EmployeeInteractionTypeCode,
	FileTypeCode,
	GenderCode,
	PayerPreferenceTypeCode,
	ServiceTypeCode,
} from 'src/app/api/models';
import { ScreeningTypeCode } from './code-types.models';
import { CountryTypeCode } from './country-type.model';

export interface SelectOptions<k = string | number | boolean> {
	code: k;
	desc: string;
	extra?: string;
}

export const CaseSubStatuses: SelectOptions[] = [
	{ desc: 'Applicant Information', code: CaseSubStatusCode.ApplicantInformation },
	{ desc: 'Confirmation Of Fingerprints', code: CaseSubStatusCode.Fingerprints },
	{ desc: 'Self Disclosure', code: CaseSubStatusCode.SelfDisclosure },
	{ desc: 'Opportunity To Respond', code: CaseSubStatusCode.OpportunityToRespond },
];

export const EmployeeInteractionTypes: SelectOptions[] = [
	{ desc: 'Children', code: EmployeeInteractionTypeCode.Children },
	{ desc: 'Vulnerable Adults', code: EmployeeInteractionTypeCode.Adults },
	{ desc: 'Children and Vulnerable Adults', code: EmployeeInteractionTypeCode.ChildrenAndAdults },
];

export const FileTypes: SelectOptions[] = [
	{ desc: 'Applicant Consent Form', code: FileTypeCode.ApplicantConsentForm },
	{ desc: 'Applicant Information', code: FileTypeCode.ApplicantInformation },
	{ desc: 'Armoured Car Guard', code: FileTypeCode.ArmouredCarGuard },
	{ desc: 'Armoured Vehicle Purpose', code: FileTypeCode.ArmouredVehiclePurpose },
	{ desc: 'Armoured Vehicle Rationale', code: FileTypeCode.ArmouredVehicleRationale },
	{ desc: 'BC Companies Registration Verification', code: FileTypeCode.BcCompaniesRegistrationVerification },
	{ desc: 'BC Services Card', code: FileTypeCode.BcServicesCard },
	{ desc: 'Birth Certificate', code: FileTypeCode.BirthCertificate },
	{ desc: 'Body Armour Purpose', code: FileTypeCode.BodyArmourPurpose },
	{ desc: 'Body Armour Rationale', code: FileTypeCode.BodyArmourRationale },
	{ desc: 'Business Insurance', code: FileTypeCode.BusinessInsurance },
	{ desc: 'Canadian Citizenship', code: FileTypeCode.CanadianCitizenship },
	{ desc: 'Canadian Firearms License', code: FileTypeCode.CanadianFirearmsLicense },
	{ desc: 'Canadian Native Status Card', code: FileTypeCode.CanadianNativeStatusCard },
	{ desc: 'Certificate Of Advanced Security Training', code: FileTypeCode.CertificateOfAdvancedSecurityTraining },
	{ desc: 'Confirmation Letter From Superior Officer', code: FileTypeCode.ConfirmationLetterFromSuperiorOfficer },
	{ desc: 'Confirmation Of Fingerprints', code: FileTypeCode.ConfirmationOfFingerprints },
	{ desc: 'Convicted Offence', code: FileTypeCode.ConvictedOffence },
	{ desc: 'Criminal Charges', code: FileTypeCode.CriminalCharges },
	{ desc: 'Driver License', code: FileTypeCode.DriverLicense },
	{ desc: 'Govt Issued Photo Id', code: FileTypeCode.GovtIssuedPhotoId },
	{ desc: 'Legal Name Change', code: FileTypeCode.LegalNameChange },
	{ desc: 'Legal Work Status', code: FileTypeCode.LegalWorkStatus },
	{ desc: 'Letter Of No Conflict', code: FileTypeCode.LetterOfNoConflict },
	{ desc: 'Locksmith', code: FileTypeCode.Locksmith },
	{ desc: 'Mental Health Condition Form', code: FileTypeCode.MentalHealthConditionForm },
	{ desc: 'Passport', code: FileTypeCode.Passport },
	{ desc: 'Permanent Residence Card', code: FileTypeCode.PermanentResidenceCard },
	{ desc: 'Photograph', code: FileTypeCode.Photograph },
	{ desc: 'Private Investigator', code: FileTypeCode.PrivateInvestigator },
	{ desc: 'Private Investigator Under Supervision', code: FileTypeCode.PrivateInvestigatorUnderSupervision },
	{ desc: 'Security Alarm Installer', code: FileTypeCode.SecurityAlarmInstaller },
	{ desc: 'Security Consultant', code: FileTypeCode.SecurityConsultant },
	{ desc: 'Security Guard', code: FileTypeCode.SecurityGuard },
	{ desc: 'Self Disclosure', code: FileTypeCode.SelfDisclosure },
	{ desc: 'Validation Certificate', code: FileTypeCode.ValidationCertificate },
	{ desc: 'Opportunity To Respond', code: FileTypeCode.OpportunityToRespond },
];

export const ScreeningTypes: SelectOptions[] = [
	{ desc: 'Contractor', code: ScreeningTypeCode.Contractor },
	{ desc: 'Licensee', code: ScreeningTypeCode.Licensee },
	{ desc: 'Staff', code: ScreeningTypeCode.Staff },
];

export const PayerPreferenceTypes: SelectOptions[] = [
	{ desc: 'Applicant', code: PayerPreferenceTypeCode.Applicant },
	{ desc: 'Organization', code: PayerPreferenceTypeCode.Organization },
];

export const ServiceTypes: SelectOptions[] = [
	{ desc: 'Armoured Vehicle Permit', code: ServiceTypeCode.ArmouredVehiclePermit },
	{ desc: 'Body Armour Permit', code: ServiceTypeCode.BodyArmourPermit },
	{ desc: 'Combined Criminal Check (CSH ONLY)', code: ServiceTypeCode.PssoVs },
	{ desc: 'CRRP - Employee', code: ServiceTypeCode.CrrpEmployee },
	{ desc: 'CRRP - Volunteer', code: ServiceTypeCode.CrrpVolunteer },
	{ desc: 'Foster, OOC, Adoptions and Relief Provider', code: ServiceTypeCode.Mcfd },
	{ desc: 'MDRA', code: ServiceTypeCode.Mdra },
	{ desc: 'PE-CRC', code: ServiceTypeCode.PeCrc },
	{ desc: 'PE-CRC + Vulnerable Sector', code: ServiceTypeCode.PeCrcVs },
	{ desc: 'Public Service Employment Check', code: ServiceTypeCode.Psso },
	{ desc: 'Security Worker Licence', code: ServiceTypeCode.SecurityWorkerLicence },
	{ desc: 'Security Business Licence', code: ServiceTypeCode.SecurityBusinessLicence },
	{
		desc: 'Security Business Licence Controlling Member CRC',
		code: ServiceTypeCode.SecurityBusinessLicenceControllingMemberCrc,
	},
];

export const GenderTypes: SelectOptions[] = [
	{ desc: 'M', code: GenderCode.M },
	{ desc: 'F', code: GenderCode.F },
	{ desc: 'X', code: GenderCode.U },
];

export const ContactAuthorizationTypes: SelectOptions[] = [
	{ desc: 'Primary Authorized Contact', code: ContactAuthorizationTypeCode.Primary },
	{ desc: 'Authorized Contact', code: ContactAuthorizationTypeCode.Contact },
];

export const ApplicationPortalStatusTypes: SelectOptions[] = [
	{ desc: 'Draft', code: ApplicationPortalStatusCode.Draft },
	{
		desc: 'Verify Identity',
		code: ApplicationPortalStatusCode.VerifyIdentity,
		extra: `The applicant has submitted their CRC application, and the organization must confirm they have checked the applicant's government-issued photo ID`,
	},
	{
		desc: 'In Progress',
		code: ApplicationPortalStatusCode.InProgress,
		extra: 'The application is currently undergoing the screening process',
	},
	{
		desc: 'Payment Pending',
		code: ApplicationPortalStatusCode.AwaitingPayment,
		extra: 'The organization or the applicant must pay the application fee',
	},
	{
		desc: 'Awaiting Third Party',
		code: ApplicationPortalStatusCode.AwaitingThirdParty,
		extra: 'Waiting for information from an external party',
	},
	{
		desc: 'Awaiting Applicant',
		code: ApplicationPortalStatusCode.AwaitingApplicant,
		extra: 'Waiting for the applicant to provide additional information',
	},
	{
		desc: 'Under Assessment',
		code: ApplicationPortalStatusCode.UnderAssessment,
		extra: 'The application is in risk assessment',
	},
	{ desc: 'Incomplete', code: ApplicationPortalStatusCode.Incomplete, extra: 'Incomplete application received' },
	{
		desc: 'Completed - Cleared',
		code: ApplicationPortalStatusCode.CompletedCleared,
		extra: 'Criminal record check completed - no risk',
	},
	{
		desc: 'Completed - Risk Found',
		code: ApplicationPortalStatusCode.RiskFound,
		extra: 'The applicant is not cleared due to risk found',
	},
	{
		desc: 'Closed - No Response',
		code: ApplicationPortalStatusCode.ClosedNoResponse,
		extra: 'No response from applicant',
	},
	{
		desc: 'Closed - No Consent',
		code: ApplicationPortalStatusCode.ClosedNoConsent,
		extra: 'The applicant did not consent to the CRC',
	},
	{
		desc: 'Cancelled by Organization',
		code: ApplicationPortalStatusCode.CancelledByOrganization,
		extra: 'Organization cancelled the application',
	},
	{
		desc: 'Cancelled by Applicant',
		code: ApplicationPortalStatusCode.CancelledByApplicant,
		extra: 'The applicant cancelled their application',
	},
	{ desc: 'Refund Requested', code: ApplicationPortalStatusCode.RefundRequested },
];

export const CountryTypes: SelectOptions[] = [
	{ desc: 'Canada', code: CountryTypeCode.Canada },
	{ desc: 'United States of America', code: CountryTypeCode.UnitedStatesofAmerica },
	{ desc: 'Afghanistan', code: CountryTypeCode.Afghanistan },
	{ desc: 'Åland Islands', code: CountryTypeCode.ÅlandIslands },
	{ desc: 'Albania', code: CountryTypeCode.Albania },
	{ desc: 'Algeria', code: CountryTypeCode.Algeria },
	{ desc: 'American Samoa', code: CountryTypeCode.AmericanSamoa },
	{ desc: 'Andorra', code: CountryTypeCode.Andorra },
	{ desc: 'Angola', code: CountryTypeCode.Angola },
	{ desc: 'Anguilla', code: CountryTypeCode.Anguilla },
	{ desc: 'Antarctica', code: CountryTypeCode.Antarctica },
	{ desc: 'Antigua and Barbuda', code: CountryTypeCode.AntiguaandBarbuda },
	{ desc: 'Argentina', code: CountryTypeCode.Argentina },
	{ desc: 'Armenia', code: CountryTypeCode.Armenia },
	{ desc: 'Aruba', code: CountryTypeCode.Aruba },
	{ desc: 'Australia', code: CountryTypeCode.Australia },
	{ desc: 'Austria', code: CountryTypeCode.Austria },
	{ desc: 'Azerbaijan', code: CountryTypeCode.Azerbaijan },
	{ desc: 'Bahamas (the)', code: CountryTypeCode.Bahamas },
	{ desc: 'Bahrain', code: CountryTypeCode.Bahrain },
	{ desc: 'Bangladesh', code: CountryTypeCode.Bangladesh },
	{ desc: 'Barbados', code: CountryTypeCode.Barbados },
	{ desc: 'Belarus', code: CountryTypeCode.Belarus },
	{ desc: 'Belgium', code: CountryTypeCode.Belgium },
	{ desc: 'Belize', code: CountryTypeCode.Belize },
	{ desc: 'Benin', code: CountryTypeCode.Benin },
	{ desc: 'Bermuda', code: CountryTypeCode.Bermuda },
	{ desc: 'Bhutan', code: CountryTypeCode.Bhutan },
	{ desc: 'Bolivia (Plurinational State of)', code: CountryTypeCode.Bolivia },
	{ desc: 'Bonaire, Sint Eustatius and Saba', code: CountryTypeCode.Bonaire },
	{ desc: 'Bosnia and Herzegovina', code: CountryTypeCode.BosniaandHerzegovina },
	{ desc: 'Botswana', code: CountryTypeCode.Botswana },
	{ desc: 'Bouvet Island', code: CountryTypeCode.BouvetIsland },
	{ desc: 'Brazil', code: CountryTypeCode.Brazil },
	{ desc: 'British Indian Ocean Territory (the)', code: CountryTypeCode.BritishIndianOceanTerritory },
	{ desc: 'Brunei Darussalam', code: CountryTypeCode.BruneiDarussalam },
	{ desc: 'Bulgaria', code: CountryTypeCode.Bulgaria },
	{ desc: 'Burkina Faso', code: CountryTypeCode.BurkinaFaso },
	{ desc: 'Burundi', code: CountryTypeCode.Burundi },
	{ desc: 'Cabo Verde', code: CountryTypeCode.CaboVerde },
	{ desc: 'Cambodia', code: CountryTypeCode.Cambodia },
	{ desc: 'Cameroon', code: CountryTypeCode.Cameroon },
	{ desc: 'Cayman Islands (the)', code: CountryTypeCode.CaymanIslands },
	{ desc: 'Central African Republic (the)', code: CountryTypeCode.CentralAfricanRepublic },
	{ desc: 'Chad', code: CountryTypeCode.Chad },
	{ desc: 'Chile', code: CountryTypeCode.Chile },
	{ desc: 'China', code: CountryTypeCode.China },
	{ desc: 'Christmas Island', code: CountryTypeCode.ChristmasIsland },
	{ desc: 'Cocos (Keeling) Islands (the)', code: CountryTypeCode.CocosIslands },
	{ desc: 'Colombia', code: CountryTypeCode.Colombia },
	{ desc: 'Comoros (the)', code: CountryTypeCode.Comoros },
	{ desc: 'Congo (the Democratic Republic of the)', code: CountryTypeCode.DemocraticRepublicCongo },
	{ desc: 'Congo (the)', code: CountryTypeCode.Congo },
	{ desc: 'Cook Islands (the)', code: CountryTypeCode.CookIslands },
	{ desc: 'Costa Rica', code: CountryTypeCode.CostaRica },
	{ desc: "Côte d'Ivoire", code: CountryTypeCode.CôtedIvoire },
	{ desc: 'Croatia', code: CountryTypeCode.Croatia },
	{ desc: 'Cuba', code: CountryTypeCode.Cuba },
	{ desc: 'Curaçao', code: CountryTypeCode.Curaçao },
	{ desc: 'Cyprus', code: CountryTypeCode.Cyprus },
	{ desc: 'Czechia', code: CountryTypeCode.Czechia },
	{ desc: 'Denmark', code: CountryTypeCode.Denmark },
	{ desc: 'Djibouti', code: CountryTypeCode.Djibouti },
	{ desc: 'Dominica', code: CountryTypeCode.Dominica },
	{ desc: 'Dominican Republic (the)', code: CountryTypeCode.DominicanRepublic },
	{ desc: 'Ecuador', code: CountryTypeCode.Ecuador },
	{ desc: 'Egypt', code: CountryTypeCode.Egypt },
	{ desc: 'El Salvador', code: CountryTypeCode.ElSalvador },
	{ desc: 'Equatorial Guinea', code: CountryTypeCode.EquatorialGuinea },
	{ desc: 'Eritrea', code: CountryTypeCode.Eritrea },
	{ desc: 'Estonia', code: CountryTypeCode.Estonia },
	{ desc: 'Eswatini', code: CountryTypeCode.Switzerland },
	{ desc: 'Ethiopia', code: CountryTypeCode.Ethiopia },
	{ desc: 'Falkland Islands (the) [Malvinas]', code: CountryTypeCode.FalklandIslands },
	{ desc: 'Faroe Islands (the)', code: CountryTypeCode.FaroeIslands },
	{ desc: 'Fiji', code: CountryTypeCode.Fiji },
	{ desc: 'Finland', code: CountryTypeCode.Finland },
	{ desc: 'France', code: CountryTypeCode.France },
	{ desc: 'French Guiana', code: CountryTypeCode.FrenchGuiana },
	{ desc: 'French Polynesia', code: CountryTypeCode.FrenchPolynesia },
	{ desc: 'French Southern Territories (the)', code: CountryTypeCode.FrenchSouthernTerritories },
	{ desc: 'Gabon', code: CountryTypeCode.Gabon },
	{ desc: 'Gambia (the)', code: CountryTypeCode.Gambia },
	{ desc: 'Georgia', code: CountryTypeCode.Georgia },
	{ desc: 'Germany', code: CountryTypeCode.Germany },
	{ desc: 'Ghana', code: CountryTypeCode.Ghana },
	{ desc: 'Gibraltar', code: CountryTypeCode.Gibraltar },
	{ desc: 'Greece', code: CountryTypeCode.Greece },
	{ desc: 'Greenland', code: CountryTypeCode.Greenland },
	{ desc: 'Grenada', code: CountryTypeCode.Grenada },
	{ desc: 'Guadeloupe', code: CountryTypeCode.Guadeloupe },
	{ desc: 'Guam', code: CountryTypeCode.Guam },
	{ desc: 'Guatemala', code: CountryTypeCode.Guatemala },
	{ desc: 'Guernsey', code: CountryTypeCode.Guernsey },
	{ desc: 'Guinea', code: CountryTypeCode.Guinea },
	{ desc: 'Guinea-Bissau', code: CountryTypeCode.GuineaBissau },
	{ desc: 'Guyana', code: CountryTypeCode.Guyana },
	{ desc: 'Haiti', code: CountryTypeCode.Haiti },
	{ desc: 'Heard Island and McDonald Islands', code: CountryTypeCode.HeardIslandandMcDonaldIslands },
	{ desc: 'Holy See (the)', code: CountryTypeCode.HolySee },
	{ desc: 'Honduras', code: CountryTypeCode.Honduras },
	{ desc: 'Hong Kong', code: CountryTypeCode.HongKong },
	{ desc: 'Hungary', code: CountryTypeCode.Hungary },
	{ desc: 'Iceland', code: CountryTypeCode.Iceland },
	{ desc: 'India', code: CountryTypeCode.India },
	{ desc: 'Indonesia', code: CountryTypeCode.Indonesia },
	{ desc: 'Iran (Islamic Republic of)', code: CountryTypeCode.Iran },
	{ desc: 'Iraq', code: CountryTypeCode.Iraq },
	{ desc: 'Ireland', code: CountryTypeCode.Ireland },
	{ desc: 'Isle of Man', code: CountryTypeCode.IsleofMan },
	{ desc: 'Israel', code: CountryTypeCode.Israel },
	{ desc: 'Italy', code: CountryTypeCode.Italy },
	{ desc: 'Jamaica', code: CountryTypeCode.Jamaica },
	{ desc: 'Japan', code: CountryTypeCode.Japan },
	{ desc: 'Jersey', code: CountryTypeCode.Jersey },
	{ desc: 'Jordan', code: CountryTypeCode.Jordan },
	{ desc: 'Kazakhstan', code: CountryTypeCode.Kazakhstan },
	{ desc: 'Kenya', code: CountryTypeCode.Kenya },
	{ desc: 'Kiribati', code: CountryTypeCode.Kiribati },
	{ desc: "Korea (the Democratic People's Republic of)", code: CountryTypeCode.DemocraticPeoplesRepublicofKorea },
	{ desc: 'Korea (the Republic of)', code: CountryTypeCode.RepublicofKorea },
	{ desc: 'Kuwait', code: CountryTypeCode.Kuwait },
	{ desc: 'Kyrgyzstan', code: CountryTypeCode.Kyrgyzstan },
	{ desc: "Lao People's Democratic Republic (the)", code: CountryTypeCode.LaoPeople },
	{ desc: 'Latvia', code: CountryTypeCode.Latvia },
	{ desc: 'Lebanon', code: CountryTypeCode.Lebanon },
	{ desc: 'Lesotho', code: CountryTypeCode.Lesotho },
	{ desc: 'Liberia', code: CountryTypeCode.Liberia },
	{ desc: 'Libya', code: CountryTypeCode.Libya },
	{ desc: 'Liechtenstein', code: CountryTypeCode.Liechtenstein },
	{ desc: 'Lithuania', code: CountryTypeCode.Lithuania },
	{ desc: 'Luxembourg', code: CountryTypeCode.Luxembourg },
	{ desc: 'Macao', code: CountryTypeCode.Macao },
	{ desc: 'Madagascar', code: CountryTypeCode.Madagascar },
	{ desc: 'Malawi', code: CountryTypeCode.Malawi },
	{ desc: 'Malaysia', code: CountryTypeCode.Malaysia },
	{ desc: 'Maldives', code: CountryTypeCode.Maldives },
	{ desc: 'Mali', code: CountryTypeCode.Mali },
	{ desc: 'Malta', code: CountryTypeCode.Malta },
	{ desc: 'Marshall Islands (the)', code: CountryTypeCode.MarshallIslands },
	{ desc: 'Martinique', code: CountryTypeCode.Martinique },
	{ desc: 'Mauritania', code: CountryTypeCode.Mauritania },
	{ desc: 'Mauritius', code: CountryTypeCode.Mauritius },
	{ desc: 'Mayotte', code: CountryTypeCode.Mayotte },
	{ desc: 'Mexico', code: CountryTypeCode.Mexico },
	{ desc: 'Micronesia (Federated States of)', code: CountryTypeCode.Micronesia },
	{ desc: 'Moldova (the Republic of)', code: CountryTypeCode.Moldova },
	{ desc: 'Monaco', code: CountryTypeCode.Monaco },
	{ desc: 'Mongolia', code: CountryTypeCode.Mongolia },
	{ desc: 'Montenegro', code: CountryTypeCode.Montenegro },
	{ desc: 'Montserrat', code: CountryTypeCode.Montserrat },
	{ desc: 'Morocco', code: CountryTypeCode.Morocco },
	{ desc: 'Mozambique', code: CountryTypeCode.Mozambique },
	{ desc: 'Myanmar', code: CountryTypeCode.Myanmar },
	{ desc: 'Namibia', code: CountryTypeCode.Namibia },
	{ desc: 'Nauru', code: CountryTypeCode.Nauru },
	{ desc: 'Nepal', code: CountryTypeCode.Nepal },
	{ desc: 'Netherlands (the)', code: CountryTypeCode.Netherlands },
	{ desc: 'New Caledonia', code: CountryTypeCode.NewCaledonia },
	{ desc: 'New Zealand', code: CountryTypeCode.NewZealand },
	{ desc: 'Nicaragua', code: CountryTypeCode.Nicaragua },
	{ desc: 'Niger (the)', code: CountryTypeCode.Niger },
	{ desc: 'Nigeria', code: CountryTypeCode.Nigeria },
	{ desc: 'Niue', code: CountryTypeCode.Niue },
	{ desc: 'Norfolk Island', code: CountryTypeCode.NorfolkIsland },
	{ desc: 'North Macedonia', code: CountryTypeCode.NorthMacedonia },
	{ desc: 'Northern Mariana Islands (the)', code: CountryTypeCode.NorthernMarianaIslands },
	{ desc: 'Norway', code: CountryTypeCode.Norway },
	{ desc: 'Oman', code: CountryTypeCode.Oman },
	{ desc: 'Pakistan', code: CountryTypeCode.Pakistan },
	{ desc: 'Palau', code: CountryTypeCode.Palau },
	{ desc: 'Palestine, State of', code: CountryTypeCode.Palestine },
	{ desc: 'Panama', code: CountryTypeCode.Panama },
	{ desc: 'Papua New Guinea', code: CountryTypeCode.PapuaNewGuinea },
	{ desc: 'Paraguay', code: CountryTypeCode.Paraguay },
	{ desc: 'Peru', code: CountryTypeCode.Peru },
	{ desc: 'Philippines (the)', code: CountryTypeCode.Philippines },
	{ desc: 'Pitcairn', code: CountryTypeCode.Pitcairn },
	{ desc: 'Poland', code: CountryTypeCode.Poland },
	{ desc: 'Portugal', code: CountryTypeCode.Portugal },
	{ desc: 'Puerto Rico', code: CountryTypeCode.PuertoRico },
	{ desc: 'Qatar', code: CountryTypeCode.Qatar },
	{ desc: 'Réunion', code: CountryTypeCode.Réunion },
	{ desc: 'Romania', code: CountryTypeCode.Romania },
	{ desc: 'Russian Federation (the)', code: CountryTypeCode.RussianFederation },
	{ desc: 'Rwanda', code: CountryTypeCode.Rwanda },
	{ desc: 'Saint Barthélemy', code: CountryTypeCode.SaintBarthélemy },
	{ desc: 'Saint Helena, Ascension and Tristan da Cunha', code: CountryTypeCode.SaintHelena },
	{ desc: 'Saint Kitts and Nevis', code: CountryTypeCode.SaintKittsandNevis },
	{ desc: 'Saint Lucia', code: CountryTypeCode.SaintLucia },
	{ desc: 'Saint Martin (French part)', code: CountryTypeCode.SaintMartin },
	{ desc: 'Saint Pierre and Miquelon', code: CountryTypeCode.SaintPierreandMiquelon },
	{ desc: 'Saint Vincent and the Grenadines', code: CountryTypeCode.SaintVincentandtheGrenadines },
	{ desc: 'Samoa', code: CountryTypeCode.Samoa },
	{ desc: 'San Marino', code: CountryTypeCode.SanMarino },
	{ desc: 'Sao Tome and Principe', code: CountryTypeCode.SaoTomeandPrincipe },
	{ desc: 'Saudi Arabia', code: CountryTypeCode.SaudiArabia },
	{ desc: 'Senegal', code: CountryTypeCode.Senegal },
	{ desc: 'Serbia', code: CountryTypeCode.Serbia },
	{ desc: 'Seychelles', code: CountryTypeCode.Seychelles },
	{ desc: 'Sierra Leone', code: CountryTypeCode.SierraLeone },
	{ desc: 'Singapore', code: CountryTypeCode.Singapore },
	{ desc: 'Sint Maarten (Dutch part)', code: CountryTypeCode.SintMaarten },
	{ desc: 'Slovakia', code: CountryTypeCode.Slovakia },
	{ desc: 'Slovenia', code: CountryTypeCode.Slovenia },
	{ desc: 'Solomon Islands', code: CountryTypeCode.SolomonIslands },
	{ desc: 'Somalia', code: CountryTypeCode.Somalia },
	{ desc: 'South Africa', code: CountryTypeCode.SouthAfrica },
	{
		desc: 'South Georgia and the South Sandwich Islands',
		code: CountryTypeCode.SouthGeorgiaandtheSouthSandwichIslands,
	},
	{ desc: 'South Sudan', code: CountryTypeCode.SouthSudan },
	{ desc: 'Spain', code: CountryTypeCode.Spain },
	{ desc: 'Sri Lanka', code: CountryTypeCode.SriLanka },
	{ desc: 'Sudan (the)', code: CountryTypeCode.Sudan },
	{ desc: 'Suriname', code: CountryTypeCode.Suriname },
	{ desc: 'Svalbard and Jan Mayen', code: CountryTypeCode.SvalbardandJanMayen },
	{ desc: 'Sweden', code: CountryTypeCode.Sweden },
	{ desc: 'Switzerland', code: CountryTypeCode.Switzerland },
	{ desc: 'Syrian Arab Republic (the)', code: CountryTypeCode.SyrianArabRepublic },
	{ desc: 'Taiwan (Province of China)', code: CountryTypeCode.Taiwan },
	{ desc: 'Tajikistan', code: CountryTypeCode.Tajikistan },
	{ desc: 'Tanzania, the United Republic of', code: CountryTypeCode.Tanzania },
	{ desc: 'Thailand', code: CountryTypeCode.Thailand },
	{ desc: 'Timor-Leste', code: CountryTypeCode.TimorLeste },
	{ desc: 'Togo', code: CountryTypeCode.Togo },
	{ desc: 'Tokelau', code: CountryTypeCode.Tokelau },
	{ desc: 'Tonga', code: CountryTypeCode.Tonga },
	{ desc: 'Trinidad and Tobago', code: CountryTypeCode.TrinidadandTobago },
	{ desc: 'Tunisia', code: CountryTypeCode.Tunisia },
	{ desc: 'Türkiye', code: CountryTypeCode.Türkiye },
	{ desc: 'Turkmenistan', code: CountryTypeCode.Turkmenistan },
	{ desc: 'Turks and Caicos Islands (the)', code: CountryTypeCode.TurksandCaicosIslands },
	{ desc: 'Tuvalu', code: CountryTypeCode.Tuvalu },
	{ desc: 'Uganda', code: CountryTypeCode.Uganda },
	{ desc: 'Ukraine', code: CountryTypeCode.Ukraine },
	{ desc: 'United Arab Emirates (the)', code: CountryTypeCode.UnitedArabEmirates },
	{
		desc: 'United Kingdom of Great Britain and Northern Ireland (the)',
		code: CountryTypeCode.UnitedKingdomofGreatBritainandNorthernIreland,
	},
	{ desc: 'United States Minor Outlying Islands (the)', code: CountryTypeCode.UnitedStatesMinorOutlyingIslands },
	{ desc: 'Uruguay', code: CountryTypeCode.Uruguay },
	{ desc: 'Uzbekistan', code: CountryTypeCode.Uzbekistan },
	{ desc: 'Vanuatu', code: CountryTypeCode.Vanuatu },
	{ desc: 'Venezuela (Bolivarian Republic of)', code: CountryTypeCode.Venezuela },
	{ desc: 'Viet Nam', code: CountryTypeCode.VietNam },
	{ desc: 'Virgin Islands (British)', code: CountryTypeCode.BritishVirginIslands },
	{ desc: 'Virgin Islands (U.S.)', code: CountryTypeCode.USVirginIslands },
	{ desc: 'Wallis and Futuna', code: CountryTypeCode.WallisandFutuna },
	{ desc: 'Western Sahara*', code: CountryTypeCode.WesternSahara },
	{ desc: 'Yemen', code: CountryTypeCode.Yemen },
	{ desc: 'Zambia', code: CountryTypeCode.Zambia },
	{ desc: 'Zimbabwe', code: CountryTypeCode.Zimbabwe },
];
