/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AddressAutoCompleteService } from './services/address-auto-complete.service';
import { ApplicantProfileService } from './services/applicant-profile.service';
import { ConfigurationService } from './services/configuration.service';
import { DogSchoolService } from './services/dog-school.service';
import { DogTrainerLicensingService } from './services/dog-trainer-licensing.service';
import { GdsdTeamLicensingService } from './services/gdsd-team-licensing.service';
import { LicenceService } from './services/licence.service';
import { LicenceAppService } from './services/licence-app.service';
import { LicenceAppDocumentService } from './services/licence-app-document.service';
import { LoginService } from './services/login.service';
import { PaymentService } from './services/payment.service';
import { RetiredDogLicensingService } from './services/retired-dog-licensing.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AddressAutoCompleteService,
    ApplicantProfileService,
    ConfigurationService,
    DogSchoolService,
    DogTrainerLicensingService,
    GdsdTeamLicensingService,
    LicenceService,
    LicenceAppService,
    LicenceAppDocumentService,
    LoginService,
    PaymentService,
    RetiredDogLicensingService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
