/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BizProfileResponse } from '../../models/biz-profile-response';

export interface ApiMdraOrgGet$Params {
}

export function apiMdraOrgGet(http: HttpClient, rootUrl: string, params?: ApiMdraOrgGet$Params, context?: HttpContext): Observable<StrictHttpResponse<BizProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, apiMdraOrgGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BizProfileResponse>;
    })
  );
}

apiMdraOrgGet.PATH = '/api/mdra-org';
