/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MdraRegistrationCommandResponse } from '../../models/mdra-registration-command-response';
import { MdraRegistrationRequest } from '../../models/mdra-registration-request';

export interface ApiMdraRegistrationsPost$Params {
  
    /**
     * MDRARegistrationRequest data
     */
    body: MdraRegistrationRequest
}

export function apiMdraRegistrationsPost(http: HttpClient, rootUrl: string, params: ApiMdraRegistrationsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<MdraRegistrationCommandResponse>> {
  const rb = new RequestBuilder(rootUrl, apiMdraRegistrationsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MdraRegistrationCommandResponse>;
    })
  );
}

apiMdraRegistrationsPost.PATH = '/api/mdra-registrations';
