/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StakeholderAppInviteTypeCode } from '../../models/stakeholder-app-invite-type-code';
import { StakeholderInvitesCreateResponse } from '../../models/stakeholder-invites-create-response';

export interface ApiBusinessLicenceApplicationStakeholderInvitationBizContactIdGet$Params {
  bizContactId: string;
  inviteType?: StakeholderAppInviteTypeCode;
}

export function apiBusinessLicenceApplicationStakeholderInvitationBizContactIdGet(http: HttpClient, rootUrl: string, params: ApiBusinessLicenceApplicationStakeholderInvitationBizContactIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<StakeholderInvitesCreateResponse>> {
  const rb = new RequestBuilder(rootUrl, apiBusinessLicenceApplicationStakeholderInvitationBizContactIdGet.PATH, 'get');
  if (params) {
    rb.path('bizContactId', params.bizContactId, {});
    rb.query('inviteType', params.inviteType, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StakeholderInvitesCreateResponse>;
    })
  );
}

apiBusinessLicenceApplicationStakeholderInvitationBizContactIdGet.PATH = '/api/business-licence-application/stakeholder-invitation/{bizContactId}';
