/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GraduationInfo } from '../models/graduation-info';
export interface AccreditedSchoolQuestions {
  graduationInfo?: GraduationInfo;
  isGuideDog?: boolean | null;
  serviceDogTasks?: string | null;
}
