/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApplicantLoginResponse {
  applicantId?: string;
  emailAddress?: string | null;
  firstName?: string | null;
  isFirstTimeLogin?: boolean | null;
  lastName?: string | null;
  middleName1?: string | null;
  middleName2?: string | null;
}
