/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { Alias } from '../models/alias';
import { ApplicationTypeCode } from '../models/application-type-code';
import { EyeColourCode } from '../models/eye-colour-code';
import { GenderCode } from '../models/gender-code';
import { HairColourCode } from '../models/hair-colour-code';
import { HeightUnitCode } from '../models/height-unit-code';
import { PoliceOfficerRoleCode } from '../models/police-officer-role-code';
import { WeightUnitCode } from '../models/weight-unit-code';
export interface ApplicantUpdateRequest {
  aliases?: Array<Alias> | null;
  applicationTypeCode?: ApplicationTypeCode;
  criminalChargeDescription?: string | null;
  dateOfBirth?: string;
  documentKeyCodes?: Array<string> | null;
  emailAddress?: string | null;
  eyeColourCode?: EyeColourCode;
  genderCode?: GenderCode;
  givenName?: string | null;
  hairColourCode?: HairColourCode;
  hasCriminalHistory?: boolean | null;
  hasNewCriminalRecordCharge?: boolean | null;
  hasNewMentalHealthCondition?: boolean | null;
  height?: number | null;
  heightUnitCode?: HeightUnitCode;
  isPoliceOrPeaceOfficer?: boolean | null;
  isTreatedForMHC?: boolean | null;
  licenceId?: string | null;
  mailingAddress?: Address;
  middleName1?: string | null;
  middleName2?: string | null;
  otherOfficerRole?: string | null;
  phoneNumber?: string | null;
  policeOfficerRoleCode?: PoliceOfficerRoleCode;
  previousDocumentIds?: Array<string> | null;
  residentialAddress?: Address;
  surname?: string | null;
  weight?: number | null;
  weightUnitCode?: WeightUnitCode;
}
