/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ApplicationOriginTypeCode {
  Portal = 'Portal',
  Email = 'Email',
  WebForm = 'WebForm',
  Mail = 'Mail',
  Fax = 'Fax',
  GenericUpload = 'GenericUpload',
  OrganizationSubmitted = 'OrganizationSubmitted'
}
