/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ApplicationInviteStatusCode {
  Draft = 'Draft',
  Sent = 'Sent',
  Failed = 'Failed',
  Completed = 'Completed',
  Cancelled = 'Cancelled',
  Expired = 'Expired'
}
