/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BizPortalUserResponse } from '../models/biz-portal-user-response';
export interface BizPortalUserListResponse {
  maximumNumberOfAuthorizedContacts?: number | null;
  maximumNumberOfPrimaryAuthorizedContacts?: number | null;
  users?: Array<BizPortalUserResponse> | null;
}
