/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactRoleCode } from '../models/contact-role-code';
export interface BizUserLoginResponse {
  bceidBizTradeName?: string | null;
  bizId?: string;
  bizUserId?: string;
  contactRoleCode?: ContactRoleCode;
  firstName?: string | null;
  isFirstTimeLogin?: boolean | null;
  lastName?: string | null;
}
