/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface BranchInfo {
  branchAddress?: Address;
  branchEmailAddr?: string | null;
  branchId?: string | null;
  branchManager?: string | null;
  branchPhoneNumber?: string | null;
}
