/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DogInfoRenew {
  currentDogCertificate?: string | null;
  dogName?: string | null;
  isAssistanceStillRequired?: boolean;
}
