/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenderCode } from '../models/gender-code';
export interface DogInfoNewAccreditedSchool {
  dogBreed: string | null;
  dogColorAndMarkings: string | null;
  dogDateOfBirth?: string | null;
  dogGender?: GenderCode;
  dogName: string | null;
  isGuideDog: boolean;
  microchipNumber?: string | null;
  serviceDogTasks?: string | null;
}
