/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenderCode } from '../models/gender-code';
export interface DogInfoRenew {
  dogBreed?: string | null;
  dogColorAndMarkings?: string | null;
  dogDateOfBirth?: string | null;
  dogGender?: GenderCode;
  dogId?: string | null;
  dogName?: string | null;
  isAssistanceStillRequired?: boolean;
  microchipNumber?: string | null;
}
