/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum EyeColourCode {
  Blue = 'Blue',
  Brown = 'Brown',
  Black = 'Black',
  Green = 'Green',
  Hazel = 'Hazel',
  Grey = 'Grey',
  Other = 'Other'
}
