/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BizTypeCode } from '../models/biz-type-code';
import { DocumentRelatedInfo } from '../models/document-related-info';
import { DogInfoRenew } from '../models/dog-info-renew';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { ServiceTypeCode } from '../models/service-type-code';
export interface GdsdTeamLicenceAppChangeRequest {
  applicantId?: string;
  applicantOrLegalGuardianName?: string | null;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizTypeCode?: BizTypeCode;
  dateOfBirth?: string | null;
  documentKeyCodes?: Array<string> | null;
  documentRelatedInfos?: Array<DocumentRelatedInfo> | null;
  dogInfoRenew?: DogInfoRenew;
  emailAddress?: string | null;
  givenName?: string | null;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName?: string | null;
  originalLicenceId?: string;
  phoneNumber?: string | null;
  previousDocumentIds?: Array<string> | null;
  serviceTypeCode?: ServiceTypeCode;
  surname?: string | null;
}
