/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BizTypeCode } from '../models/biz-type-code';
import { Document } from '../models/document';
import { DocumentRelatedInfo } from '../models/document-related-info';
import { DogInfoNewAccreditedSchool } from '../models/dog-info-new-accredited-school';
import { DogInfoNewWithoutAccreditedSchool } from '../models/dog-info-new-without-accredited-school';
import { DogInfoRenew } from '../models/dog-info-renew';
import { GraduationInfo } from '../models/graduation-info';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { ServiceTypeCode } from '../models/service-type-code';
import { TrainingInfo } from '../models/training-info';
export interface GdsdTeamLicenceAppUpsertRequest {
  applicantId?: string;
  applicantOrLegalGuardianName?: string | null;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizTypeCode?: BizTypeCode;
  contactEmailAddress?: string | null;
  contactPhoneNumber?: string | null;
  dateOfBirth?: string;
  documentInfos?: Array<Document> | null;
  documentRelatedInfos?: Array<DocumentRelatedInfo> | null;
  dogInfoNewAccreditedSchool?: DogInfoNewAccreditedSchool;
  dogInfoNewWithoutAccreditedSchool?: DogInfoNewWithoutAccreditedSchool;
  dogInfoRenew?: DogInfoRenew;
  givenName?: string | null;
  graduationInfo?: GraduationInfo;
  isDogTrainedByAccreditedSchool?: boolean;
  licenceAppId?: string | null;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName?: string | null;
  serviceTypeCode?: ServiceTypeCode;
  surname?: string | null;
  trainingInfo?: TrainingInfo;
}
