/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum HairColourCode {
  Black = 'Black',
  Blonde = 'Blonde',
  Brown = 'Brown',
  Red = 'Red',
  Grey = 'Grey',
  Bald = 'Bald',
  White = 'White'
}
