/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum LicenceStatusCode {
  Active = 'Active',
  Inactive = 'Inactive',
  Expired = 'Expired',
  Suspended = 'Suspended',
  Preview = 'Preview'
}
