/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GoogleRecaptcha } from '../models/google-recaptcha';
export interface LicenceNumbersRequest {
  licenceNumbers?: string | null;
  recaptcha?: GoogleRecaptcha;
}
