/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LicenceAppDocumentResponse {
  documentExtension?: string | null;
  documentName?: string | null;
  documentUrlId?: string;
  licenceAppId?: string | null;
  uploadedDateTime?: string;
}
