/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LicenceStatusCode } from '../models/licence-status-code';
import { ServiceTypeCode } from '../models/service-type-code';
import { WorkerCategoryTypeCode } from '../models/worker-category-type-code';
export interface LicenceBasicAnonResponse {
  bizLegalName?: string | null;
  categoryCodes?: Array<WorkerCategoryTypeCode> | null;
  licenceHolderName?: string | null;
  licenceNumber?: string | null;
  licenceStatusCode?: LicenceStatusCode;
  nameOnCard?: string | null;
  serviceTypeCode?: ServiceTypeCode;
  showSecurityGuardAST?: boolean | null;
}
