/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum LicenceTermCode {
  NinetyDays = 'NinetyDays',
  OneYear = 'OneYear',
  TwoYears = 'TwoYears',
  ThreeYears = 'ThreeYears',
  FiveYears = 'FiveYears'
}
