/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MdraRegistrationCommandResponse {
  hasPotentialDuplicate?: boolean | null;
  registrationId?: string | null;
}
