/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BranchInfo } from '../models/branch-info';
export interface MdraRegistrationRequest {
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizAddress?: Address;
  bizEmailAddress?: string | null;
  bizLegalName?: string | null;
  bizMailingAddress?: Address;
  bizManagerFirstName?: string | null;
  bizManagerLastName?: string | null;
  bizManagerMiddleName?: string | null;
  bizOwnerFirstName?: string | null;
  bizOwnerLastName?: string | null;
  bizOwnerMiddleName?: string | null;
  bizPhoneNumber?: string | null;
  bizTradeName?: string | null;
  branches?: Array<BranchInfo> | null;
  documentKeyCodes?: Array<string> | null;
}
