/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BranchInfo } from '../models/branch-info';
export interface MdraRegistrationResponse {
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizAddress?: Address;
  bizEmailAddress?: string | null;
  bizLegalName?: string | null;
  bizMailingAddress?: Address;
  bizManagerEmailAddress?: string | null;
  bizManagerFullName?: string | null;
  bizManagerPhoneNumber?: string | null;
  bizOwnerGivenNames?: string | null;
  bizOwnerSurname?: string | null;
  bizPhoneNumber?: string | null;
  bizTradeName?: string | null;
  branches?: Array<BranchInfo> | null;
  expiredLicenceId?: string | null;
  registrationId?: string | null;
  registrationNumber?: string | null;
}
