/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OidcConfiguration {
  clientId?: string | null;
  identityProvider?: string | null;
  issuer?: string | null;
  postLogoutRedirectUri?: string | null;
  responseType?: string | null;
  scope?: string | null;
}
