/* tslint:disable */
/* eslint-disable */
import { Alias } from './alias';
import { ApplicationTypeCode } from './application-type-code';
import { ArmouredVehiclePermitReasonCode } from './armoured-vehicle-permit-reason-code';
import { BodyArmourPermitReasonCode } from './body-armour-permit-reason-code';
import { BusinessTypeCode } from './business-type-code';
import { DocumentExpiredInfo } from './document-expired-info';
import { EmployerPrimaryAddress } from './employer-primary-address';
import { EyeColourCode } from './eye-colour-code';
import { GenderCode } from './gender-code';
import { HairColourCode } from './hair-colour-code';
import { HeightUnitCode } from './height-unit-code';
import { LicenceTermCode } from './licence-term-code';
import { MailingAddress } from './mailing-address';
import { PoliceOfficerRoleCode } from './police-officer-role-code';
import { ResidentialAddress } from './residential-address';
import { WeightUnitCode } from './weight-unit-code';
import { WorkerLicenceTypeCode } from './worker-licence-type-code';
export interface PermitAppAnonymousSubmitRequest {
  agreeToCompleteAndAccurate?: null | boolean;
  aliases?: null | Array<Alias>;
  applicationTypeCode?: ApplicationTypeCode;
  armouredVehiclePermitReasonCodes?: null | Array<ArmouredVehiclePermitReasonCode>;
  bcDriversLicenceNumber?: null | string;
  bodyArmourPermitReasonCodes?: null | Array<BodyArmourPermitReasonCode>;
  businessTypeCode?: BusinessTypeCode;
  carryAndUseRestraints?: null | boolean;
  contactEmailAddress?: null | string;
  contactPhoneNumber?: null | string;
  dateOfBirth?: null | string;
  documentExpiredInfos?: null | Array<DocumentExpiredInfo>;
  documentKeyCodes?: null | Array<string>;
  employerName?: null | string;
  employerPrimaryAddress?: EmployerPrimaryAddress;
  expiredLicenceId?: null | string;
  expiredLicenceNumber?: null | string;
  eyeColourCode?: EyeColourCode;
  genderCode?: GenderCode;
  givenName?: null | string;
  hairColourCode?: HairColourCode;
  hasBcDriversLicence?: null | boolean;
  hasCriminalHistory?: null | boolean;
  hasExpiredLicence?: null | boolean;
  hasLegalNameChanged?: null | boolean;
  hasNewCriminalRecordCharge?: null | boolean;
  hasNewMentalHealthCondition?: null | boolean;
  hasPreviousName?: null | boolean;
  height?: null | number;
  heightUnitCode?: HeightUnitCode;
  isCanadianCitizen?: null | boolean;
  isCanadianResident?: null | boolean;
  isMailingTheSameAsResidential?: null | boolean;
  isPoliceOrPeaceOfficer?: null | boolean;
  isTreatedForMHC?: null | boolean;
  licenceTermCode?: LicenceTermCode;
  mailingAddressData?: MailingAddress;
  middleName1?: null | string;
  middleName2?: null | string;
  oneLegalName?: null | boolean;
  originalApplicationId?: null | string;
  originalLicenceId?: null | string;
  otherOfficerRole?: null | string;
  permitOtherRequiredReason?: null | string;
  policeOfficerRoleCode?: PoliceOfficerRoleCode;
  previousDocumentIds?: null | Array<string>;
  rationale?: null | string;
  reprint?: null | boolean;
  residentialAddressData?: ResidentialAddress;
  supervisorEmailAddress?: null | string;
  supervisorName?: null | string;
  supervisorPhoneNumber?: null | string;
  surname?: null | string;
  useBcServicesCardPhoto?: null | boolean;
  weight?: null | number;
  weightUnitCode?: WeightUnitCode;
  workerLicenceTypeCode?: WorkerLicenceTypeCode;
}
