/* tslint:disable */
/* eslint-disable */
import { Address } from '../models/address';
import { Alias } from '../models/alias';
import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { ArmouredVehiclePermitReasonCode } from '../models/armoured-vehicle-permit-reason-code';
import { BizTypeCode } from '../models/biz-type-code';
import { BodyArmourPermitReasonCode } from '../models/body-armour-permit-reason-code';
import { Document } from '../models/document';
import { DocumentExpiredInfo } from '../models/document-expired-info';
import { EyeColourCode } from '../models/eye-colour-code';
import { GenderCode } from '../models/gender-code';
import { HairColourCode } from '../models/hair-colour-code';
import { HeightUnitCode } from '../models/height-unit-code';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { ResidentialAddress } from '../models/residential-address';
import { WeightUnitCode } from '../models/weight-unit-code';
import { WorkerLicenceTypeCode } from '../models/worker-licence-type-code';
export interface PermitAppUpsertRequest {
  agreeToCompleteAndAccurate?: boolean | null;
  aliases?: Array<Alias> | null;
  applicantId?: string;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationTypeCode?: ApplicationTypeCode;
  armouredVehiclePermitReasonCodes?: Array<ArmouredVehiclePermitReasonCode> | null;
  bcDriversLicenceNumber?: string | null;
  bizTypeCode?: BizTypeCode;
  bodyArmourPermitReasonCodes?: Array<BodyArmourPermitReasonCode> | null;
  dateOfBirth?: string | null;
  documentExpiredInfos?: Array<DocumentExpiredInfo> | null;
  documentInfos?: Array<Document> | null;
  emailAddress?: string | null;
  employerName?: string | null;
  employerPrimaryAddress?: Address;
  expiredLicenceId?: string | null;
  eyeColourCode?: EyeColourCode;
  genderCode?: GenderCode;
  givenName?: string | null;
  hairColourCode?: HairColourCode;
  hasBcDriversLicence?: boolean | null;
  hasCriminalHistory?: boolean | null;
  hasExpiredLicence?: boolean | null;
  hasLegalNameChanged?: boolean | null;
  hasNewCriminalRecordCharge?: boolean | null;
  hasPreviousName?: boolean | null;
  height?: number | null;
  heightUnitCode?: HeightUnitCode;
  isCanadianCitizen?: boolean | null;
  isCanadianResident?: boolean | null;
  isMailingTheSameAsResidential?: boolean | null;
  licenceAppId?: string | null;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName1?: string | null;
  middleName2?: string | null;
  oneLegalName?: boolean | null;
  permitOtherRequiredReason?: string | null;
  phoneNumber?: string | null;
  rationale?: string | null;
  residentialAddress?: ResidentialAddress;
  supervisorEmailAddress?: string | null;
  supervisorName?: string | null;
  supervisorPhoneNumber?: string | null;
  surname?: string | null;
  weight?: number | null;
  weightUnitCode?: WeightUnitCode;
  workerLicenceTypeCode?: WorkerLicenceTypeCode;
}
