/* tslint:disable */
/* eslint-disable */
import { Address } from './address';
import { Alias } from './alias';
import { ApplicationTypeCode } from './application-type-code';
import { ArmouredVehiclePermitReasonCode } from './armoured-vehicle-permit-reason-code';
import { BizTypeCode } from './biz-type-code';
import { BodyArmourPermitReasonCode } from './body-armour-permit-reason-code';
import { DocumentExpiredInfo } from './document-expired-info';
import { EyeColourCode } from './eye-colour-code';
import { GenderCode } from './gender-code';
import { HairColourCode } from './hair-colour-code';
import { HeightUnitCode } from './height-unit-code';
import { LicenceTermCode } from './licence-term-code';
import { MailingAddress } from './mailing-address';
import { ResidentialAddress } from './residential-address';
import { WeightUnitCode } from './weight-unit-code';
import { WorkerLicenceTypeCode } from './worker-licence-type-code';
export interface PermitAppSubmitRequest {
  agreeToCompleteAndAccurate?: null | boolean;
  aliases?: null | Array<Alias>;
  applicationTypeCode?: ApplicationTypeCode;
  armouredVehiclePermitReasonCodes?: null | Array<ArmouredVehiclePermitReasonCode>;
  bcDriversLicenceNumber?: null | string;
  bizTypeCode?: BizTypeCode;
  bodyArmourPermitReasonCodes?: null | Array<BodyArmourPermitReasonCode>;
  criminalChargeDescription?: null | string;
  dateOfBirth?: null | string;
  documentExpiredInfos?: null | Array<DocumentExpiredInfo>;
  documentKeyCodes?: null | Array<string>;
  emailAddress?: null | string;
  employerName?: null | string;
  employerPrimaryAddress?: Address;
  expiredLicenceId?: null | string;
  eyeColourCode?: EyeColourCode;
  genderCode?: GenderCode;
  givenName?: null | string;
  hairColourCode?: HairColourCode;
  hasBcDriversLicence?: null | boolean;
  hasCriminalHistory?: null | boolean;
  hasExpiredLicence?: null | boolean;
  hasLegalNameChanged?: null | boolean;
  hasNewCriminalRecordCharge?: null | boolean;
  hasPreviousName?: null | boolean;
  height?: null | number;
  heightUnitCode?: HeightUnitCode;
  isCanadianCitizen?: null | boolean;
  isCanadianResident?: null | boolean;
  isMailingTheSameAsResidential?: null | boolean;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName1?: null | string;
  middleName2?: null | string;
  oneLegalName?: null | boolean;
  originalApplicationId?: null | string;
  originalLicenceId?: null | string;
  permitOtherRequiredReason?: null | string;
  phoneNumber?: null | string;
  previousDocumentIds?: null | Array<string>;
  rationale?: null | string;
  reprint?: null | boolean;
  residentialAddress?: ResidentialAddress;
  supervisorEmailAddress?: null | string;
  supervisorName?: null | string;
  supervisorPhoneNumber?: null | string;
  surname?: null | string;
  weight?: null | number;
  weightUnitCode?: WeightUnitCode;
  workerLicenceTypeCode?: WorkerLicenceTypeCode;
}
