/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum PoliceOfficerRoleCode {
  AuxiliaryorReserveConstable = 'AuxiliaryorReserveConstable',
  SheriffDeputySheriff = 'SheriffDeputySheriff',
  CorrectionsOfficer = 'CorrectionsOfficer',
  CourtAppointedBailiff = 'CourtAppointedBailiff',
  SpecialProvincialOrMunicipalConstable = 'SpecialProvincialOrMunicipalConstable',
  PoliceOfficer = 'PoliceOfficer',
  PoliceOfficerRetired = 'PoliceOfficerRetired',
  Other = 'Other',
  None = 'None'
}
