/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationPortalStatusCode } from '../models/application-portal-status-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BizTypeCode } from '../models/biz-type-code';
import { Document } from '../models/document';
import { DocumentRelatedInfo } from '../models/document-related-info';
import { DogInfo } from '../models/dog-info';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { ServiceTypeCode } from '../models/service-type-code';
export interface RetiredDogLicenceAppResponse {
  applicantId?: string;
  applicantOrLegalGuardianName?: string | null;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationPortalStatus?: ApplicationPortalStatusCode;
  applicationTypeCode?: ApplicationTypeCode;
  bizTypeCode?: BizTypeCode;
  caseNumber?: string | null;
  confirmDogLiveWithYouAfterRetire?: boolean | null;
  currentGDSDCertificateNumber?: string | null;
  dateOfBirth?: string | null;
  documentInfos?: Array<Document> | null;
  documentRelatedInfos?: Array<DocumentRelatedInfo> | null;
  dogInfo?: DogInfo;
  dogRetiredDate?: string | null;
  emailAddress?: string | null;
  givenName?: string | null;
  licenceAppId?: string | null;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName?: string | null;
  phoneNumber?: string | null;
  serviceTypeCode?: ServiceTypeCode;
  surname?: string | null;
}
