/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum StakeholderAppInviteTypeCode {
  New = 'New',
  Update = 'Update',
  CreateShellApp = 'CreateShellApp'
}
