/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SwlContactInfo {
  bizContactId?: string | null;
  contactId?: string | null;
  licenceId?: string | null;
}
