/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OtherTraining } from '../models/other-training';
import { TrainingSchoolInfo } from '../models/training-school-info';
export interface TrainingInfo {
  hasAttendedTrainingSchool?: boolean | null;
  otherTrainings?: Array<OtherTraining> | null;
  schoolTrainings?: Array<TrainingSchoolInfo> | null;
  specializedTasksWhenPerformed?: string | null;
}
