/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailingAddress } from '../models/mailing-address';
export interface TrainingSchoolContactInfo {
  totalTrainingHours?: number;
  trainingBizContactEmailAddress?: string | null;
  trainingBizContactGivenName?: string | null;
  trainingBizContactPhoneNumber?: string | null;
  trainingBizContactSurname?: string | null;
  trainingBizMailingAddress?: MailingAddress;
  trainingBizName?: string | null;
  trainingDateFrom?: string | null;
  trainingDateTo?: string | null;
  trainingName?: string | null;
  whatLearned?: string | null;
}
