/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OtherTraining } from '../models/other-training';
import { TrainingSchoolContactInfo } from '../models/training-school-contact-info';
export interface TrainingInfo {
  hasAttendedTrainingSchool?: boolean;
  otherTrainings?: Array<OtherTraining> | null;
  trainingSchoolContactInfos?: Array<TrainingSchoolContactInfo> | null;
}
