/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailingAddress } from '../models/mailing-address';
export interface TrainingInfo {
  dogTrainerCredential?: string | null;
  hoursPracticingSkill?: string | null;
  specializedTasks?: string | null;
  totalTrainingHours?: number;
  trainerEmailAddress?: string | null;
  trainerGivenName?: string | null;
  trainerPhoneNumber?: string | null;
  trainerSurname?: string | null;
  trainingBizContactEmailAddress?: string | null;
  trainingBizContactGivenName?: string | null;
  trainingBizContactPhoneNumber?: string | null;
  trainingBizContactSurname?: string | null;
  trainingBizMailingAddress?: MailingAddress;
  trainingBizName?: string | null;
  trainingDateFrom?: string | null;
  trainingDateTo?: string | null;
  trainingDetail?: string | null;
  trainingName?: string | null;
  trainingTime?: string | null;
  usePersonalDogTrainer?: boolean;
  whatLearned?: string | null;
  whenPerformed?: string | null;
}
