/* tslint:disable */
/* eslint-disable */
import { Alias } from './alias';
import { ApplicationTypeCode } from './application-type-code';
import { BizTypeCode } from './biz-type-code';
import { Document } from './document';
import { DocumentExpiredInfo } from './document-expired-info';
import { EyeColourCode } from './eye-colour-code';
import { GenderCode } from './gender-code';
import { HairColourCode } from './hair-colour-code';
import { HeightUnitCode } from './height-unit-code';
import { LicenceTermCode } from './licence-term-code';
import { MailingAddress } from './mailing-address';
import { PoliceOfficerRoleCode } from './police-officer-role-code';
import { ResidentialAddress } from './residential-address';
import { WeightUnitCode } from './weight-unit-code';
import { WorkerCategoryTypeCode } from './worker-category-type-code';
import { WorkerLicenceTypeCode } from './worker-licence-type-code';
export interface WorkerLicenceAppUpsertRequest {
  agreeToCompleteAndAccurate?: null | boolean;
  aliases?: null | Array<Alias>;
  applicantId?: string;
  applicationTypeCode?: ApplicationTypeCode;
  bcDriversLicenceNumber?: null | string;
  bizTypeCode?: BizTypeCode;
  carryAndUseRestraints?: null | boolean;
  categoryCodes?: null | Array<WorkerCategoryTypeCode>;
  dateOfBirth?: null | string;
  documentExpiredInfos?: null | Array<DocumentExpiredInfo>;
  documentInfos?: null | Array<Document>;
  emailAddress?: null | string;
  expiredLicenceId?: null | string;
  eyeColourCode?: EyeColourCode;
  genderCode?: GenderCode;
  givenName?: null | string;
  hairColourCode?: HairColourCode;
  hasBcDriversLicence?: null | boolean;
  hasCriminalHistory?: null | boolean;
  hasExpiredLicence?: null | boolean;
  hasLegalNameChanged?: null | boolean;
  hasNewCriminalRecordCharge?: null | boolean;
  hasNewMentalHealthCondition?: null | boolean;
  hasPreviousName?: null | boolean;
  height?: null | number;
  heightUnitCode?: HeightUnitCode;
  isCanadianCitizen?: null | boolean;
  isDogsPurposeDetectionDrugs?: null | boolean;
  isDogsPurposeDetectionExplosives?: null | boolean;
  isDogsPurposeProtection?: null | boolean;
  isMailingTheSameAsResidential?: null | boolean;
  isPoliceOrPeaceOfficer?: null | boolean;
  isTreatedForMHC?: null | boolean;
  licenceAppId?: null | string;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName1?: null | string;
  middleName2?: null | string;
  oneLegalName?: null | boolean;
  otherOfficerRole?: null | string;
  phoneNumber?: null | string;
  policeOfficerRoleCode?: PoliceOfficerRoleCode;
  residentialAddress?: ResidentialAddress;
  surname?: null | string;
  useDogs?: null | boolean;
  weight?: null | number;
  weightUnitCode?: WeightUnitCode;
  workerLicenceTypeCode?: WorkerLicenceTypeCode;
}
