/* tslint:disable */
/* eslint-disable */
import { Alias } from '../models/alias';
import { ApplicationOriginTypeCode } from '../models/application-origin-type-code';
import { ApplicationPortalStatusCode } from '../models/application-portal-status-code';
import { ApplicationTypeCode } from '../models/application-type-code';
import { BizTypeCode } from '../models/biz-type-code';
import { Document } from '../models/document';
import { DocumentExpiredInfo } from '../models/document-expired-info';
import { EyeColourCode } from '../models/eye-colour-code';
import { GenderCode } from '../models/gender-code';
import { HairColourCode } from '../models/hair-colour-code';
import { HeightUnitCode } from '../models/height-unit-code';
import { LicenceTermCode } from '../models/licence-term-code';
import { MailingAddress } from '../models/mailing-address';
import { PoliceOfficerRoleCode } from '../models/police-officer-role-code';
import { ResidentialAddress } from '../models/residential-address';
import { WeightUnitCode } from '../models/weight-unit-code';
import { WorkerCategoryTypeCode } from '../models/worker-category-type-code';
import { WorkerLicenceTypeCode } from '../models/worker-licence-type-code';
export interface WorkerLicenceAppResponse {
  agreeToCompleteAndAccurate?: boolean | null;
  aliases?: Array<Alias> | null;
  applicationOriginTypeCode?: ApplicationOriginTypeCode;
  applicationPortalStatus?: ApplicationPortalStatusCode;
  applicationTypeCode?: ApplicationTypeCode;
  bcDriversLicenceNumber?: string | null;
  bizTypeCode?: BizTypeCode;
  carryAndUseRestraints?: boolean | null;
  caseNumber?: string | null;
  categoryCodes?: Array<WorkerCategoryTypeCode> | null;
  dateOfBirth?: string | null;
  documentExpiredInfos?: Array<DocumentExpiredInfo> | null;
  documentInfos?: Array<Document> | null;
  emailAddress?: string | null;
  expiredLicenceId?: string | null;
  expiredLicenceNumber?: string | null;
  expiryDate?: string | null;
  eyeColourCode?: EyeColourCode;
  genderCode?: GenderCode;
  givenName?: string | null;
  hairColourCode?: HairColourCode;
  hasBcDriversLicence?: boolean | null;
  hasCriminalHistory?: boolean | null;
  hasExpiredLicence?: boolean | null;
  hasLegalNameChanged?: boolean | null;
  hasNewCriminalRecordCharge?: boolean | null;
  hasNewMentalHealthCondition?: boolean | null;
  hasPreviousName?: boolean | null;
  height?: number | null;
  heightUnitCode?: HeightUnitCode;
  isCanadianCitizen?: boolean | null;
  isDogsPurposeDetectionDrugs?: boolean | null;
  isDogsPurposeDetectionExplosives?: boolean | null;
  isDogsPurposeProtection?: boolean | null;
  isMailingTheSameAsResidential?: boolean | null;
  isPoliceOrPeaceOfficer?: boolean | null;
  isTreatedForMHC?: boolean | null;
  licenceAppId?: string;
  licenceTermCode?: LicenceTermCode;
  mailingAddress?: MailingAddress;
  middleName1?: string | null;
  middleName2?: string | null;
  oneLegalName?: boolean | null;
  otherOfficerRole?: string | null;
  phoneNumber?: string | null;
  policeOfficerRoleCode?: PoliceOfficerRoleCode;
  residentialAddress?: ResidentialAddress;
  soleProprietorBizAppId?: string | null;
  surname?: string | null;
  useDogs?: boolean | null;
  weight?: number | null;
  weightUnitCode?: WeightUnitCode;
  workerLicenceTypeCode?: WorkerLicenceTypeCode;
}
