/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum WorkerCategoryTypeCode {
  ArmouredCarGuard = 'ArmouredCarGuard',
  BodyArmourSales = 'BodyArmourSales',
  ClosedCircuitTelevisionInstaller = 'ClosedCircuitTelevisionInstaller',
  ElectronicLockingDeviceInstaller = 'ElectronicLockingDeviceInstaller',
  FireInvestigator = 'FireInvestigator',
  Locksmith = 'Locksmith',
  LocksmithUnderSupervision = 'LocksmithUnderSupervision',
  PrivateInvestigator = 'PrivateInvestigator',
  PrivateInvestigatorUnderSupervision = 'PrivateInvestigatorUnderSupervision',
  SecurityGuard = 'SecurityGuard',
  SecurityGuardUnderSupervision = 'SecurityGuardUnderSupervision',
  SecurityAlarmInstallerUnderSupervision = 'SecurityAlarmInstallerUnderSupervision',
  SecurityAlarmInstaller = 'SecurityAlarmInstaller',
  SecurityAlarmMonitor = 'SecurityAlarmMonitor',
  SecurityAlarmResponse = 'SecurityAlarmResponse',
  SecurityAlarmSales = 'SecurityAlarmSales',
  SecurityConsultant = 'SecurityConsultant'
}
