/* tslint:disable */
/* eslint-disable */
import { Alias } from './alias';
import { ApplicationTypeCode } from './application-type-code';
import { DocumentBase } from './document-base';
import { EyeColourCode } from './eye-colour-code';
import { GenderCode } from './gender-code';
import { HairColourCode } from './hair-colour-code';
import { HeightUnitCode } from './height-unit-code';
import { LicenceTermCode } from './licence-term-code';
import { MailingAddress } from './mailing-address';
import { PoliceOfficerRoleCode } from './police-officer-role-code';
import { ResidentialAddress } from './residential-address';
import { WeightUnitCode } from './weight-unit-code';
import { WorkerCategoryTypeCode } from './worker-category-type-code';
import { WorkerLicenceTypeCode } from './worker-licence-type-code';
export interface WorkerLicenceAppAnonymousSubmitRequestJson {
  aliases?: null | Array<Alias>;
  applicationTypeCode?: ApplicationTypeCode;
  bcDriversLicenceNumber?: null | string;
  carryAndUseRestraints?: null | boolean;
  categoryCodes?: null | Array<WorkerCategoryTypeCode>;
  contactEmailAddress?: null | string;
  contactPhoneNumber?: null | string;
  dateOfBirth?: null | string;
  documentInfos?: null | Array<DocumentBase>;
  expiredLicenceId?: null | string;
  expiredLicenceNumber?: null | string;
  eyeColourCode?: EyeColourCode;
  fileKeyCodes?: null | Array<string>;
  genderCode?: GenderCode;
  givenName?: null | string;
  hairColourCode?: HairColourCode;
  hasBcDriversLicence?: null | boolean;
  hasCriminalHistory?: null | boolean;
  hasExpiredLicence?: null | boolean;
  hasPreviousName?: null | boolean;
  height?: null | number;
  heightUnitCode?: HeightUnitCode;
  isCanadianCitizen?: null | boolean;
  isDogsPurposeDetectionDrugs?: null | boolean;
  isDogsPurposeDetectionExplosives?: null | boolean;
  isDogsPurposeProtection?: null | boolean;
  isMailingTheSameAsResidential?: null | boolean;
  isPoliceOrPeaceOfficer?: null | boolean;
  isSoleProprietor?: null | boolean;
  isTreatedForMHC?: null | boolean;
  licenceTermCode?: LicenceTermCode;
  mailingAddressData?: MailingAddress;
  middleName1?: null | string;
  middleName2?: null | string;
  oneLegalName?: null | boolean;
  otherOfficerRole?: null | string;
  policeOfficerRoleCode?: PoliceOfficerRoleCode;
  residentialAddressData?: ResidentialAddress;
  surname?: null | string;
  useBcServicesCardPhoto?: null | boolean;
  useDogs?: null | boolean;
  weight?: null | number;
  weightUnitCode?: WeightUnitCode;
  workerLicenceTypeCode?: WorkerLicenceTypeCode;
}
