name: Dynamics Helper Build

on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - "!src/Spd.Presentation.Licensing/**"
      - "!src/Spd.Presentation.Screening/**"
      - .github/workflows/dynamics-helper-build.yml
      - .github/workflows/docker-build-template.yml

  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - "!src/Spd.Presentation.Licensing/**"
      - "!src/Spd.Presentation.Screening/**"
      - .github/workflows/dynamics-helper-build.yml
      - .github/workflows/docker-build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-build-template.yml
    with:
      IMAGE_CONTEXT: src
      IMAGE_FILE: src/dynamics.dockerfile
      IMAGE_NAME: ${{ github.repository }}/dynamics-helper
      REGISTRY: ghcr.io
    secrets:
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
