name: Dynamics Helper Build

on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - src/**
      - "!src/Spd.Presentation.Licensing/**"
      - "!src/Spd.Presentation.Screening/**"
      - "!src/Spd.Manager.Licence/**"
      - "!src/Spd.Manager.Screening/**"
      - .github/workflows/dynamics-helper-build.yml
      - .github/workflows/docker-build-template.yml

  pull_request:    
    paths:
      - src/**
      - "!src/Spd.Presentation.Licensing/**"
      - "!src/Spd.Presentation.Screening/**"
      - "!src/Spd.Manager.Licence/**"
      - "!src/Spd.Manager.Screening/**"
      - .github/workflows/dynamics-helper-build.yml
      - .github/workflows/docker-build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-build-template.yml
    with:
      IMAGE_CONTEXT: src
      IMAGE_FILE: src/dynamics.dockerfile
      IMAGE_NAME: ${{ github.repository }}/dynamics-helper
      # REGISTRY: ghcr.io
      REGISTRY: artifacts.developer.gov.bc.ca/sfe7-dev/
    secrets:
      # REGISTRY_USER: ${{ github.actor }}
      # REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
