name: fe-cd.yml

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/fe-cd.yml
  pull_request:
    branches: 
      - main
    paths:
      - frontend/**
      - .github/workflows/fe-cd.yml

jobs:
  build-fe:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./frontend
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/frontend:latest
        run: |
          docker build --tag ${IMAGE} -f ${CONTEXT}/Dockerfile ${CONTEXT}
          docker push ${IMAGE}
