name: Licensing Portal Build

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - '!src/Spd.Presentation.Dynamics/**'
      - '!src/Spd.Presentation.Screening/**'      
      - .github/workflows/licensing-portal-build.yml
      - .github/workflows/docker-build-template.yml

  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - '!src/Spd.Presentation.Dynamics/**'
      - '!src/Spd.Presentation.Screening/**'      
      - .github/workflows/licensing-portal-build.yml
      - .github/workflows/docker-build-template.yml
  
jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-build-template.yml
    with:
      IMAGE_CONTEXT: src
      IMAGE_FILE: src/licensing-portal.dockerfile
      IMAGE_NAME: ${{ github.repository }}/licensing-portal
      # REGISTRY: ghcr.io
      REGISTRY: artifacts.gov.bc.ca/sfe7-dev
    secrets:
      # REGISTRY_USER: ${{ github.actor }}
      # REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      RESITRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
