name: Pull Request - Organization Registration FrontEnd Build

on:
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/org-registration-fe-cd.yml

jobs:
  build-deploy-organization-registration:
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: frontend
      DOCKER_FILE: frontend/Dockerfile
      DOCKER_IMAGE_NAME: organization-registration
      DOCKER_PUSH: false
    secrets: inherit
