name: Generate Release Notes

on:
  release:
    types:
      - created

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Release Notes
        id: notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: custom-config.yml

      - name: Upload Release Notes
        run: |
          gh release edit ${{ github.event.release.id }} \
            --notes "${{ steps.notes.outputs.release_notes }}"
