name: Generate Release Notes

on:
  workflow_dispatch: # Enables manual triggering
    inputs:
      release_tag:
        description: "Tag of the release"
        required: true
        default: "release-1.2.1"
  release:
    types:
      - created

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Release Notes
        id: notes
        uses: release-drafter/release-drafter@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-name: custom-config.yml

      - name: Upload Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure token is available
        run: |
          gh release edit ${{ github.event.release.tag_name }} \
            --notes "${{ steps.notes.outputs.release_notes }}"
