name: Screening Portal Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/**'
      - develop
    paths:
      - src/**
      - "!src/Spd.Presentation.Dynamics/**"
      - "!src/Spd.Presentation.Licensing/**"
      - "!src/Spd.Manager.Licence/**"
      - .github/workflows/screening-portal-build.yml
      - .github/workflows/docker-build-template.yml

  pull_request:
    paths:
      - src/**
      - "!src/Spd.Presentation.Dynamics/**"
      - "!src/Spd.Presentation.Licensing/**"
      - "!src/Spd.Manager.Licence/**"
      - .github/workflows/screening-portal-build.yml
      - .github/workflows/docker-build-template.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/docker-build-template.yml
    with:
      IMAGE_CONTEXT: src
      IMAGE_FILE: src/screening-portal.dockerfile
      IMAGE_NAME: ${{ github.repository }}/screening-portal
      REGISTRY: ghcr.io
      # REGISTRY: artifacts.developer.gov.bc.ca/sfe7-dev/
    secrets:
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      # REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      # REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
