name: Screening Portal Scheduled Deployment For Dev testing

#temp to deploy to dev for some internal testing
on:
  push:
    branches:
      - dev-temp-screening

jobs:
  build-deploy-screening-portal-to-dev:
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: src
      DOCKER_FILE: src/screening-portal.dockerfile
      DOCKER_IMAGE_NAME: screening-portal
      DOCKER_IMAGE_TAG: latest
    secrets: inherit
